cache:
  paths:
    - .cache

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CARGO_HOME: "$CI_PROJECT_DIR/.cache/cargo"
  SUBDAEMON:
    value: "hsmd:remote_hsmd_vls"
    description: "use the inplace hsmd replacement (default), or the standalone version `hsmd:remote_hsmd` or the socket version: `hsmd:remote_hsmd_socket`"
  LIGHTNING_REF:
    value: ""
    description: "rebase onto the ref (e.g. master) from the upstream c-lightning repository"

stages:
  - vls
  - test

compile-vls:
  stage: vls
  image: rust:1.60.0
  timeout: 30m
  script:
    # we don't need to rebase lightning here, but fail fast if rebase fails
    # - ./scripts/maybe-rebase "$LIGHTNING_REF"
    # latest rust images seem to require rustfmt for cargo build
    - apt-get update
    - apt-get install -y protobuf-compiler
    - rustup component add rustfmt
    - make setup
    - make list-versions
    - (cd vls && git status)
    - (cd vls && git clean -f && cargo clean)
    - (cd vls/lightning-storage-server && git clean -f && cargo clean)
    - (cd vls && git status)
    - (cd vls && cargo build --locked --bins)
    - (cd vls/lightning-storage-server && cargo build --locked --bins)
    # replace the symbolic links w/ actual files
    - mkdir -p newbin && cp -L bin/* newbin/ && rm -rf bin && mv newbin bin
    - ls -l bin
    - bin/remote_hsmd_vls --git-desc
    - bin/remote_hsmd_socket_test --git-desc
  artifacts:
    paths:
      - bin/vlsd
      - bin/lssd
      - bin/remote_hsmd_vls
      - bin/remote_hsmd_socket
      - bin/remote_hsmd_socket_test
      - bin/remote_hsmd_serial

test-inplace-standard:
  stage: test
  image: ubuntu
  script:
    - ./scripts/install-additional
    # - ./scripts/maybe-rebase "$LIGHTNING_REF"
    - git submodule update --init --recursive
    - make list-versions
    - ./scripts/setup-remote-hsmd
    - source scripts/setup-env
    - remote_hsmd_vls --git-desc
    - cd lightning
    - bash -ex .github/scripts/setup.sh  # missing `set -e` internally
    - bash -ex .github/scripts/build.sh  # missing `set -e` internally

test-inplace:
  stage: test
  image: ubuntu
  variables:
    EXPERIMENTAL_FEATURES: "1"
  script:
    - ./scripts/install-additional
    # - ./scripts/maybe-rebase "$LIGHTNING_REF"
    - git submodule update --init --recursive
    - make list-versions
    - ./scripts/setup-remote-hsmd
    - source scripts/setup-env
    - remote_hsmd_vls --git-desc
    - cd lightning
    - bash -ex .github/scripts/setup.sh  # missing `set -e` internally
    - bash -ex .github/scripts/build.sh  # missing `set -e` internally

test-standalone:
  stage: test
  image: ubuntu
  variables:
    EXPERIMENTAL_FEATURES: "1"
    SUBDAEMON: hsmd:remote_hsmd
  script:
    - ./scripts/install-additional
    # - ./scripts/maybe-rebase "$LIGHTNING_REF"
    - git submodule update --init --recursive
    - make list-versions
    - ./scripts/setup-remote-hsmd
    - source scripts/setup-env
    - cd lightning
    - bash -ex .github/scripts/setup.sh  # missing `set -e` internally
    - bash -ex .github/scripts/build.sh  # missing `set -e` internally

test-socket:
  stage: test
  image: ubuntu
  variables:
    EXPERIMENTAL_FEATURES: "1"
    SUBDAEMON: hsmd:remote_hsmd_socket_test
  script:
    - ./scripts/install-additional
    # - ./scripts/maybe-rebase "$LIGHTNING_REF"
    - git submodule update --init --recursive
    - make list-versions
    - ./scripts/setup-remote-hsmd
    - source scripts/setup-env
    - remote_hsmd_socket_test --git-desc
    - cd lightning
    - bash -ex .github/scripts/setup.sh  # missing `set -e` internally
    # - export PYTEST_ADDOPTS="-ktest_pay"
    - bash -ex .github/scripts/build.sh  # missing `set -e` internally

test-permissive:
  stage: test
  image: ubuntu
  variables:
    EXPERIMENTAL_FEATURES: "1"
    VLS_PERMISSIVE: "1"
    SUBDAEMON: hsmd:remote_hsmd_socket_test
  script:
    - ./scripts/install-additional
    # - ./scripts/maybe-rebase "$LIGHTNING_REF"
    - git submodule update --init --recursive
    - make list-versions
    - ./scripts/setup-remote-hsmd
    - source scripts/setup-env
    - remote_hsmd_socket_test --git-desc
    - cd lightning
    - bash -ex .github/scripts/setup.sh  # missing `set -e` internally
    # - export PYTEST_ADDOPTS="-ktest_pay"
    - bash -ex .github/scripts/build.sh  # missing `set -e` internally
