image: ubuntu

build:
  stage: build
  script:
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -yy -qq git ca-certificates sudo tzdata python3 python3-pip python3-setuptools python3-dev python-is-python3
    - python3 --version
    - pip3 install --upgrade pip
    - git submodule update --init
    - bash -x scripts/setup-remote-hsmd
    - cd lightning
    - bash -ex .github/scripts/setup.sh
    - bash -ex .github/scripts/build.sh
