#!/usr/bin/env -S uv run
# /// script
# dependencies = [
#   "pyyaml",
#   "click",
#   "pydantic",
# ]
# ///

import os
import sys
import ast
from pathlib import Path
from typing import Dict, List, Optional, Set

import click
import yaml
from pydantic import BaseModel, Field, RootModel, ValidationError

# --- Configuration ---
# These are the default values for the command-line options.
DEFAULT_SOURCE_DIR = "lightning/tests"
DEFAULT_TARGET_DIR = "tests"
DEFAULT_EXCLUSIONS_FILE = "test_exclusions.yml"
DEFAULT_SOURCE_IMPORT_ROOT = "lightning"


# --- Pydantic Schema for test_exclusions.yml ---

class ScriptConfig(BaseModel):
    """Defines global configuration for the script, like a preamble."""
    preamble: str = ""

class ExclusionSpec(RootModel[Dict[str, str]]):
    """
    Defines the exclusion rules for a single test file.
    It can either exclude all tests via '__all__' or specific tests by name.
    """
    root: Dict[str, str]

    def get_all_exclusion_reason(self) -> Optional[str]:
        """Returns the reason if the entire file is excluded, otherwise None."""
        return self.root.get("__all__")

    def get_excluded_tests(self) -> Set[str]:
        """Returns a set of individually excluded test function names."""
        return {k for k in self.root if k != "__all__"}


class ExclusionFile(BaseModel):
    """
    Represents the entire exclusion configuration file, separating global
    config from the per-file exclusion rules.
    """
    config: ScriptConfig = Field(default_factory=ScriptConfig)
    exclusions: Dict[str, ExclusionSpec] = Field(default_factory=dict)


# --- Core Logic ---

class TestFinder(ast.NodeVisitor):
    """
    Uses the Abstract Syntax Tree (AST) to find all function definitions
    that look like tests (i.e., start with 'test_').
    """
    def __init__(self):
        self.test_functions: List[str] = []

    def visit_FunctionDef(self, node: ast.FunctionDef):
        if node.name.startswith('test_'):
            self.test_functions.append(node.name)
        self.generic_visit(node)


def load_exclusions(exclusions_file: Path) -> ExclusionFile:
    """Loads and validates the YAML exclusion file using Pydantic."""
    if not exclusions_file.exists():
        click.echo(f"INFO: Exclusions file not found at '{exclusions_file}'. Proceeding without exclusions.")
        return ExclusionFile()
    
    with open(exclusions_file, 'r', encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    
    try:
        return ExclusionFile.model_validate(data)
    except ValidationError as e:
        click.echo(f"ERROR: Invalid format in exclusions file '{exclusions_file}':\n{e}", err=True)
        sys.exit(1)


def generate_wrapper_file_content(
    source_file_path: Path,
    tests_to_import: List[str],
    source_import_root: str,
    preamble: str = "",
    excluded_tests: Dict[str, str] = None
) -> str:
    """Generates the content for the new wrapper test file."""
    
    if excluded_tests is None:
        excluded_tests = {}
    
    module_path = ".".join(source_file_path.with_suffix('').parts)

    if source_import_root and not module_path.startswith(source_import_root):
        path_parts = source_file_path.with_suffix('').parts
        try:
            root_index = path_parts.index(source_import_root)
            module_path = ".".join(path_parts[root_index:])
        except ValueError:
            click.echo(f"WARNING: Could not find '{source_import_root}' in path '{source_file_path}'. Import statements may be incorrect.", err=True)
            module_path = ".".join(path_parts)

    header = [
        "# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.",
        f"# Source file: {source_file_path}",
        "#",
        "# To update these tests, run the synchronization script.",
        "# To selectively exclude tests, modify the 'test_exclusions.yml' file.",
        "",
        "# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name",
        "# flake8: noqa",
        ""
    ]
    
    # Add the preamble if it exists
    if preamble:
        header.extend([
            "# --- Preamble from config: Start ---",
            preamble.strip(),
            "# --- Preamble from config: End ---",
            ""
        ])

    if not tests_to_import and not excluded_tests:
        header.append("# All tests in the source file are excluded or the file is empty.")
        return "\n".join(header)

    # Generate imports for active tests (not excluded)
    imports = []
    for test in sorted(tests_to_import):
        imports.append(f"from {module_path} import {test}")
    
    # Generate imports and wrappers for excluded tests
    skipped_imports = []
    for test in sorted(excluded_tests.keys()):
        reason = excluded_tests[test]
        skipped_imports.extend([
            f"from {module_path} import {test} as _{test}",
            "",
            f'{test} = pytest.mark.skip("{reason}")(_{test})',
            ""
        ])
    
    content_parts = header
    if imports:
        content_parts.extend(imports)
        content_parts.append("")
    if skipped_imports:
        content_parts.extend(skipped_imports)
    
    return "\n".join(content_parts)


def sync_tests(source_dir: Path, target_dir: Path, config: ExclusionFile, source_import_root: str):
    """
    Main function to synchronize tests from the source to the target directory.
    """
    click.echo(f"Starting test synchronization...")
    click.echo(f"  Source: {source_dir}")
    click.echo(f"  Target: {target_dir}")
    click.echo("-" * 20)

    synced_files: Set[Path] = set()
    preamble = config.config.preamble
    exclusions = config.exclusions

    if preamble:
        click.echo("INFO: Using preamble from configuration file.")

    # Walk through the source directory
    for root, _, files in os.walk(source_dir):
        for filename in files:
            if filename.startswith("test_") and filename.endswith(".py"):
                source_file_path = Path(root) / filename
                relative_path = source_file_path.relative_to(source_dir)
                target_file_path = target_dir / relative_path

                synced_files.add(target_file_path)

                # --- Find tests in the source file ---
                try:
                    source_code = source_file_path.read_text(encoding="utf-8")
                    tree = ast.parse(source_code)
                    finder = TestFinder()
                    finder.visit(tree)
                    all_tests = set(finder.test_functions)
                except Exception as e:
                    click.echo(f"WARNING: Could not parse {source_file_path}. Skipping. Error: {e}", err=True)
                    continue

                # --- Check for exclusions ---
                exclusion_key = str(relative_path)
                file_exclusions = exclusions.get(exclusion_key)

                excluded_test_dict = {}
                if file_exclusions:
                    if reason := file_exclusions.get_all_exclusion_reason():
                        click.echo(f"Excluding entire file: {relative_path} (Reason: {reason})")
                        # Mark all tests as excluded with the same reason
                        excluded_test_dict = {test: reason for test in all_tests}
                        tests_to_import = []
                    else:
                        excluded_tests = file_exclusions.get_excluded_tests()
                        # Build dictionary of excluded tests with their reasons
                        excluded_test_dict = {test: file_exclusions.root[test] for test in excluded_tests if test in all_tests}
                        tests_to_import = sorted(list(all_tests - excluded_tests))
                else:
                    tests_to_import = sorted(list(all_tests))

                if not tests_to_import and all_tests:
                    click.echo(f"INFO: All tests in {relative_path} are excluded.")
                elif excluded_test_dict:
                    click.echo(f"INFO: In {relative_path}, excluding tests: {', '.join(sorted(excluded_test_dict.keys()))}")

                # --- Generate and write the wrapper file ---
                click.echo(f"Syncing: {relative_path} -> {target_file_path}")
                wrapper_content = generate_wrapper_file_content(
                    source_file_path, tests_to_import, source_import_root, preamble, excluded_test_dict
                )
                
                target_file_path.parent.mkdir(parents=True, exist_ok=True)
                target_file_path.write_text(wrapper_content, encoding="utf-8")

    # --- Cleanup: Remove stale files from target directory ---
    click.echo("-" * 20)
    click.echo("Cleaning up stale test files in target directory...")
    if target_dir.is_dir():
        for root, _, files in os.walk(target_dir):
            for filename in files:
                if filename.startswith("test_") and filename.endswith(".py"):
                    target_file = Path(root) / filename
                    if target_file not in synced_files:
                        click.echo(f"Removing stale file: {target_file}")
                        target_file.unlink()

    click.echo("\nSynchronization complete.")


@click.command(context_settings=dict(help_option_names=['-h', '--help']))
@click.option(
    "--source-dir",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    default=DEFAULT_SOURCE_DIR,
    show_default=True,
    help="The source directory containing the original tests.",
)
@click.option(
    "--target-dir",
    type=click.Path(file_okay=False, path_type=Path),
    default=DEFAULT_TARGET_DIR,
    show_default=True,
    help="The target directory where wrapper test files will be created.",
)
@click.option(
    "--exclusions",
    "exclusions_file",
    type=click.Path(dir_okay=False, path_type=Path),
    default=DEFAULT_EXCLUSIONS_FILE,
    show_default=True,
    help="Path to the YAML file specifying tests to exclude.",
)
@click.option(
    "--source-import-root",
    type=str,
    default=DEFAULT_SOURCE_IMPORT_ROOT,
    show_default=True,
    help="The root package name for imports from the source project.",
)
def main(source_dir: Path, target_dir: Path, exclusions_file: Path, source_import_root: str):
    """
    Synchronizes pytest tests from a source project to a wrapper project,
    allowing for selective exclusion of tests via a YAML configuration file.
    """
    config_data = load_exclusions(exclusions_file)
    sync_tests(source_dir, target_dir, config_data, source_import_root)


if __name__ == "__main__":
    main()
