#!/usr/bin/env -S uv run
# /// script
# dependencies = [
#   "pyyaml",
#   "click",
#   "pydantic",
# ]
# ///

import os
import sys
import ast
from pathlib import Path
from typing import Dict, List, Optional, Set

import click
import yaml
from pydantic import BaseModel, Field, RootModel, ValidationError

# --- Configuration ---
# These are the default values for the command-line options.
DEFAULT_SOURCE_DIR = "lightning/tests"
DEFAULT_TARGET_DIR = "tests"
DEFAULT_CONFIG_FILE = "test_config.yml"
DEFAULT_SOURCE_IMPORT_ROOT = "lightning"


# --- Pydantic Schema for test_config.yml ---

class ScriptConfig(BaseModel):
    """Defines global configuration for the script, like a preamble."""
    preamble: str = ""

class TestFileConfig(BaseModel):
    """
    Defines the configuration for a single test file.
    Uses inclusion-based approach: only tests listed in 'include' are imported,
    and tests in 'skip' are imported but marked with pytest.mark.skip.
    """
    include: List[str] = Field(default_factory=list, description="List of test functions to include (import normally)")
    skip: Dict[str, str] = Field(default_factory=dict, description="Dict of test functions to skip with reasons {test_name: reason}")

    def get_included_tests(self) -> Set[str]:
        """Returns a set of test function names to include."""
        return set(self.include)

    def get_skipped_tests(self) -> Dict[str, str]:
        """Returns a dict of test function names to skip with their reasons."""
        return self.skip


class TestConfig(BaseModel):
    """
    Represents the entire test configuration file, separating global
    config from the per-file test rules.
    """
    config: ScriptConfig = Field(default_factory=ScriptConfig)
    tests: Dict[str, TestFileConfig] = Field(default_factory=dict)


# --- Core Logic ---

class TestFinder(ast.NodeVisitor):
    """
    Uses the Abstract Syntax Tree (AST) to find all function definitions
    that look like tests (i.e., start with 'test_').
    """
    def __init__(self):
        self.test_functions: List[str] = []

    def visit_FunctionDef(self, node: ast.FunctionDef):
        if node.name.startswith('test_'):
            self.test_functions.append(node.name)
        self.generic_visit(node)


def load_config(config_file: Path) -> TestConfig:
    """Loads and validates the YAML configuration file using Pydantic."""
    if not config_file.exists():
        click.echo(f"INFO: Configuration file not found at '{config_file}'. Creating empty config.")
        return TestConfig()
    
    with open(config_file, 'r', encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    
    try:
        return TestConfig.model_validate(data)
    except ValidationError as e:
        click.echo(f"ERROR: Invalid format in configuration file '{config_file}':\n{e}", err=True)
        sys.exit(1)


def generate_wrapper_file_content(
    source_file_path: Path,
    included_tests: List[str],
    skipped_tests: Dict[str, str],
    source_import_root: str,
    preamble: str = "",
) -> str:
    """Generates the content for the new wrapper test file."""
    
    module_path = ".".join(source_file_path.with_suffix('').parts)

    if source_import_root and not module_path.startswith(source_import_root):
        path_parts = source_file_path.with_suffix('').parts
        try:
            root_index = path_parts.index(source_import_root)
            module_path = ".".join(path_parts[root_index:])
        except ValueError:
            click.echo(f"WARNING: Could not find '{source_import_root}' in path '{source_file_path}'. Import statements may be incorrect.", err=True)
            module_path = ".".join(path_parts)

    header = [
        "# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.",
        f"# Source file: {source_file_path}",
        "#",
        "# To update these tests, run the synchronization script.",
        "# To selectively include/skip tests, modify the 'test_config.yml' file.",
        "",
        "# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name",
        "# flake8: noqa",
        ""
    ]
    
    # Add the preamble if it exists
    if preamble:
        header.extend([
            "# --- Preamble from config: Start ---",
            preamble.strip(),
            "# --- Preamble from config: End ---",
            ""
        ])

    if not included_tests and not skipped_tests:
        header.append("# No tests are configured for inclusion or skipping in this file.")
        return "\n".join(header)

    # Generate imports for included tests (not skipped)
    imports = []
    for test in sorted(included_tests):
        imports.append(f"from {module_path} import {test} as _{test}")
        imports.append("")
        imports.append(f"{test} = _{test}")
        imports.append("")
    
    # Generate imports and wrappers for skipped tests
    skipped_imports = []
    for test in sorted(skipped_tests.keys()):
        reason = skipped_tests[test]
        skipped_imports.extend([
            f"from {module_path} import {test} as _{test}",
            "",
            f'{test} = pytest.mark.skip("{reason}")(_{test})',
            ""
        ])
    
    content_parts = header
    if imports:
        content_parts.extend(imports)
    if skipped_imports:
        content_parts.extend(skipped_imports)
    
    return "\n".join(content_parts)


def sync_tests(source_dir: Path, target_dir: Path, config: TestConfig, source_import_root: str):
    """
    Main function to synchronize tests from the source to the target directory.
    """
    click.echo(f"Starting test synchronization...")
    click.echo(f"  Source: {source_dir}")
    click.echo(f"  Target: {target_dir}")
    click.echo("-" * 20)

    synced_files: Set[Path] = set()
    preamble = config.config.preamble
    test_configs = config.tests

    if preamble:
        click.echo("INFO: Using preamble from configuration file.")

    # Walk through the source directory
    for root, _, files in os.walk(source_dir):
        for filename in files:
            if filename.startswith("test_") and filename.endswith(".py"):
                source_file_path = Path(root) / filename
                relative_path = source_file_path.relative_to(source_dir)
                target_file_path = target_dir / relative_path

                synced_files.add(target_file_path)

                # --- Find tests in the source file ---
                try:
                    source_code = source_file_path.read_text(encoding="utf-8")
                    tree = ast.parse(source_code)
                    finder = TestFinder()
                    finder.visit(tree)
                    all_tests = set(finder.test_functions)
                except Exception as e:
                    click.echo(f"WARNING: Could not parse {source_file_path}. Skipping. Error: {e}", err=True)
                    continue

                # --- Check for test configuration ---
                config_key = str(relative_path)
                file_config = test_configs.get(config_key)

                included_tests = []
                skipped_tests = {}
                
                if file_config:
                    included_set = file_config.get_included_tests()
                    skipped_dict = file_config.get_skipped_tests()
                    
                    # Validate that included/skipped tests actually exist
                    included_tests = sorted([t for t in included_set if t in all_tests])
                    skipped_tests = {t: reason for t, reason in skipped_dict.items() if t in all_tests}
                    
                    # Warn about tests that don't exist
                    invalid_included = included_set - all_tests
                    invalid_skipped = set(skipped_dict.keys()) - all_tests
                    if invalid_included:
                        click.echo(f"WARNING: In {relative_path}, configured to include non-existent tests: {', '.join(sorted(invalid_included))}", err=True)
                    if invalid_skipped:
                        click.echo(f"WARNING: In {relative_path}, configured to skip non-existent tests: {', '.join(sorted(invalid_skipped))}", err=True)
                else:
                    # No configuration for this file - generate stub with all tests skipped
                    click.echo(f"INFO: No configuration for {relative_path}. All tests will be skipped with default reason.")
                    skipped_tests = {test: "Not yet configured for testing" for test in all_tests}

                if included_tests:
                    click.echo(f"INFO: In {relative_path}, including {len(included_tests)} tests")
                if skipped_tests:
                    click.echo(f"INFO: In {relative_path}, skipping {len(skipped_tests)} tests")

                # --- Generate and write the wrapper file ---
                click.echo(f"Syncing: {relative_path} -> {target_file_path}")
                wrapper_content = generate_wrapper_file_content(
                    source_file_path, included_tests, skipped_tests, source_import_root, preamble
                )
                
                target_file_path.parent.mkdir(parents=True, exist_ok=True)
                target_file_path.write_text(wrapper_content, encoding="utf-8")

    # --- Cleanup: Remove stale files from target directory ---
    click.echo("-" * 20)
    click.echo("Cleaning up stale test files in target directory...")
    if target_dir.is_dir():
        for root, _, files in os.walk(target_dir):
            for filename in files:
                if filename.startswith("test_") and filename.endswith(".py"):
                    target_file = Path(root) / filename
                    if target_file not in synced_files:
                        click.echo(f"Removing stale file: {target_file}")
                        target_file.unlink()

    click.echo("\nSynchronization complete.")


@click.command(context_settings=dict(help_option_names=['-h', '--help']))
@click.option(
    "--source-dir",
    type=click.Path(exists=True, file_okay=False, path_type=Path),
    default=DEFAULT_SOURCE_DIR,
    show_default=True,
    help="The source directory containing the original tests.",
)
@click.option(
    "--target-dir",
    type=click.Path(file_okay=False, path_type=Path),
    default=DEFAULT_TARGET_DIR,
    show_default=True,
    help="The target directory where wrapper test files will be created.",
)
@click.option(
    "--config",
    "config_file",
    type=click.Path(dir_okay=False, path_type=Path),
    default=DEFAULT_CONFIG_FILE,
    show_default=True,
    help="Path to the YAML file specifying which tests to include/skip.",
)
@click.option(
    "--source-import-root",
    type=str,
    default=DEFAULT_SOURCE_IMPORT_ROOT,
    show_default=True,
    help="The root package name for imports from the source project.",
)
def main(source_dir: Path, target_dir: Path, config_file: Path, source_import_root: str):
    """
    Synchronizes pytest tests from a source project to a wrapper project,
    using an inclusion-based approach. Only tests explicitly listed in the
    configuration will be included, and tests marked for skipping will be
    imported but wrapped with pytest.mark.skip.
    """
    config_data = load_config(config_file)
    sync_tests(source_dir, target_dir, config_data, source_import_root)


if __name__ == "__main__":
    main()
