[project]
name = "vls-hsmd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<4"
package-mode = false
dependencies = [
    "flaky>=3.8.1",
    "flask-socketio>=5.5.1",
    "gevent>=25.5.1",
    "mako>=1.3.0",
    "protobuf>=6.31.1",
    "pyln-client",
    "pyln-grpc-proto>=24",
    "pyln-testing",
    "pytest-timeout>=2.4.0",
    "pytest-xdist>=3.7.0",
    "rich>=14.0.0",
    "websocket-client>=1.8.0",
    "websockets>=15.0.1",
]

[tool.uv.sources]
pyln-client = { path = "lightning/contrib/pyln-client" }
pyln-testing = { path = "lightning/contrib/pyln-testing" }

[dependency-groups]
dev = [
    "poetry>=2.2.1",
]
