version: '3'
output: "prefixed"
env:
  CARGO_TARGET_DIR: "{{ .ROOT_DIR }}/target"

tasks:

  build-vls:
    dir: 'vls'
    deps:
      - build-lssd
    cmds:
      - CARGO_TARGET_DIR=../target cargo build --all --features developer

  build-lssd:
    dir: 'vls/lightning-storage-server'
    cmds:
      - CARGO_TARGET_DIR=../../target cargo build --all

  build-cln:
    dir: 'lightning'
    cmds:
      - poetry config virtualenvs.create true --local
      - poetry install
      - CARGO_TARGET_DIR=../target poetry run make -j $(nproc)
  build:
    deps:
      - build-vls
      - build-cln

  test-native:
    env:
      VLS_MODE: "cln:native"
      SUBDAEMON: "hsmd:lightning_hsmd"
    cmds:
      - uv sync
      - PATH="$PATH:{{.ROOT_DIR}}/target/debug:{{.ROOT_DIR}}/lightning/lightningd" uv run pytest tests -vvv --color=yes -sk {{ .CLI_ARGS }}

  test-vls-socket:
    env:
      VLS_MODE: "cln:socket"
      ALLOWLIST: "{{ .ROOT_DIR }}/remote_hsmd/TESTING_ALLOWLIST"
      VLS_CLN_VERSION:
        sh: ./lightning/lightningd/lightning_hsmd --version
      SUBDAEMON: "hsmd:{{ .ROOT_DIR }}/target/debug/remote_hsmd_socket"
      VLS_NETWORK: regtest
      VLS_PERMISSIVE: 1
      TEST_DEBUG: 1
      RUST_BACKTRACE: full
      PATH:
        sh: echo "$PATH:{{ .ROOT_DIR }}/target/debug:{{ .ROOT_DIR }}/lightning/lightningd:"
    deps:
      - build
    cmds:
      - uv sync
      - PATH="$PATH:{{.ROOT_DIR}}/target/debug:{{.ROOT_DIR}}/lightning/lightningd" uv run pytest tests -vvv --color=yes -n 2 --force-flaky --max-runs=5

  test-vls-socket-single:
    env:
      VLS_MODE: "cln:socket"
      ALLOWLIST: "{{ .ROOT_DIR }}/remote_hsmd/TESTING_ALLOWLIST"
      VLS_CLN_VERSION:
        sh: ./lightning/lightningd/lightning_hsmd --version
      SUBDAEMON: "hsmd:{{ .ROOT_DIR }}/target/debug/remote_hsmd_socket"
      VLS_NETWORK: regtest
      VLS_PERMISSIVE: 1
      TEST_DEBUG: 1
      RUST_BACKTRACE: full
      PATH:
        sh: echo "$PATH:{{ .ROOT_DIR }}/target/debug:{{ .ROOT_DIR }}/lightning/lightningd:"
    deps:
      - build
    cmds:
      - uv sync
      - PATH="$PATH:{{.ROOT_DIR}}/target/debug:{{.ROOT_DIR}}/lightning/lightningd" uv run pytest tests -vvv --color=yes -sk {{ .CLI_ARGS }}


  docker-image:
    cmds:
      - docker build -t vls-hsmd-tester -f Dockerfile .
  docker-test:
    deps:
      - docker-image
    cmds:
      - docker run -ti -v {{ .ROOT_DIR }}:/repo qvls-hsmd-tester task test-vls-socket
