version: '3'
output: "prefixed"
env:
  CARGO_TARGET_DIR: "{{ .ROOT_DIR }}/target"

tasks:

  build-vls:
    dir: 'vls'
    deps:
      - build-lssd
    cmds:
      - CARGO_TARGET_DIR=../target cargo build --all --features developer

  build-lssd:
    dir: 'vls/lightning-storage-server'
    cmds:
      - CARGO_TARGET_DIR=../../target cargo build --all

  configure-cln:
    dir: 'lightning'
    cmds:
      - ../scripts/build-lightning.sh ./configure --disable-valgrind CC='clang'
    status:
      - "[ -f lightning/config.vars ]"
      
  build-cln:
    dir: 'lightning'
    cmds:
      - ../scripts/build-lightning.sh ./configure --disable-valgrind CC='clang'
      - CARGO_TARGET_DIR=../target ../scripts/build-lightning.sh make
  build:
    deps:
      - build-vls
      - build-cln

  test-native:
    env:
      VLS_MODE: "cln:native"
      SUBDAEMON: "hsmd:lightning_hsmd"
      VALGRIND: "0"
    cmds:
      - uv sync
      - PATH="$PATH:{{.ROOT_DIR}}/target/debug:{{.ROOT_DIR}}/lightning/lightningd" uv run pytest tests -vvv --color=yes {{ .CLI_ARGS }}

  test-vls-socket:
    env:
      VLS_MODE: "cln:socket"
      ALLOWLIST: "{{ .ROOT_DIR }}/remote_hsmd/TESTING_ALLOWLIST"
      VLS_CLN_VERSION:
        sh: ./lightning/lightningd/lightning_hsmd --version
      SUBDAEMON: "hsmd:{{ .ROOT_DIR }}/target/debug/remote_hsmd_socket"
      VLS_NETWORK: regtest
      VLS_PERMISSIVE: 1
      TEST_DEBUG: 1
      RUST_BACKTRACE: full
      VALGRIND: "0"
      PATH:
        sh: echo "$PATH:{{ .ROOT_DIR }}/target/debug:{{ .ROOT_DIR }}/lightning/lightningd:"
    deps:
      - build
    cmds:
      - uv sync
      - PATH="$PATH:{{.ROOT_DIR}}/target/debug:{{.ROOT_DIR}}/lightning/lightningd" uv run pytest tests -vvv --color=yes -n 5 {{ .CLI_ARGS }}

  test-vls-socket-single:
    env:
      VLS_MODE: "cln:socket"
      ALLOWLIST: "{{ .ROOT_DIR }}/remote_hsmd/TESTING_ALLOWLIST"
      VLS_CLN_VERSION:
        sh: ./lightning/lightningd/lightning_hsmd --version
      SUBDAEMON: "hsmd:{{ .ROOT_DIR }}/target/debug/remote_hsmd_socket"
      VLS_NETWORK: regtest
      VLS_PERMISSIVE: 1
      TEST_DEBUG: 1
      RUST_BACKTRACE: full
      VALGRIND: "0"
      PATH:
        sh: echo "$PATH:{{ .ROOT_DIR }}/target/debug:{{ .ROOT_DIR }}/lightning/lightningd:"
    deps:
      - build
    cmds:
      - uv sync
      - PATH="$PATH:{{.ROOT_DIR}}/target/debug:{{.ROOT_DIR}}/lightning/lightningd" uv run pytest tests -vvv --color=yes -k {{ .CLI_ARGS }}

  clean:
    deps:
      - cln-clean
      - vls-clean
  cln-clean:
    directory: '.'
    cmds:
      - rm -rf target
  vls-clean:
    directory: 'vls'
    cmds:
      - make clean
      

  docker-image:
    cmds:
      - docker build -t vls-hsmd-tester -f Dockerfile .
  docker-test:
    deps:
      - docker-image
    cmds:
      - docker run -ti -v {{ .ROOT_DIR }}:/repo vls-hsmd-tester task test-vls-socket
