# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_clnrest.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_clnrest as _test_module

test_generate_certificate = pytest.mark.skip("Not yet configured for testing")(_test_module.test_generate_certificate)

test_http_headers = pytest.mark.skip("Not yet configured for testing")(_test_module.test_http_headers)

test_large_response = pytest.mark.skip("Not yet configured for testing")(_test_module.test_large_response)

test_list_methods = pytest.mark.skip("Not yet configured for testing")(_test_module.test_list_methods)

test_no_auto_start = pytest.mark.skip("Not yet configured for testing")(_test_module.test_no_auto_start)

test_numeric_msat_notification = pytest.mark.skip("Not yet configured for testing")(_test_module.test_numeric_msat_notification)

test_old_params = pytest.mark.skip("Not yet configured for testing")(_test_module.test_old_params)

test_options = pytest.mark.skip("Not yet configured for testing")(_test_module.test_options)

test_rpc_method = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rpc_method)

test_self_signed_certificates = pytest.mark.skip("Not yet configured for testing")(_test_module.test_self_signed_certificates)

test_unknown_method = pytest.mark.skip("Not yet configured for testing")(_test_module.test_unknown_method)

test_uses_grpc_plugin_certificates = pytest.mark.skip("Not yet configured for testing")(_test_module.test_uses_grpc_plugin_certificates)

test_websocket_no_rune = pytest.mark.skip("Not yet configured for testing")(_test_module.test_websocket_no_rune)

test_websocket_rune_listnotifications = pytest.mark.skip("Not yet configured for testing")(_test_module.test_websocket_rune_listnotifications)

test_websocket_rune_no_listnotifications = pytest.mark.skip("Not yet configured for testing")(_test_module.test_websocket_rune_no_listnotifications)

test_websocket_rune_readonly = pytest.mark.skip("Not yet configured for testing")(_test_module.test_websocket_rune_readonly)

test_websocket_unrestricted_rune = pytest.mark.skip("Not yet configured for testing")(_test_module.test_websocket_unrestricted_rune)

test_websocket_upgrade_header = pytest.mark.skip("Not yet configured for testing")(_test_module.test_websocket_upgrade_header)

test_websocket_wrong_rune = pytest.mark.skip("Not yet configured for testing")(_test_module.test_websocket_wrong_rune)
