# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_connection.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_connection as _test_module

test_bad_opening = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bad_opening)

test_balance = pytest.mark.skip("Not yet configured for testing")(_test_module.test_balance)

test_bench = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bench)

test_change_chaining = pytest.mark.skip("Not yet configured for testing")(_test_module.test_change_chaining)

test_channel_abandon = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_abandon)

test_channel_features = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_features)

test_channel_persistence = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_persistence)

test_channel_reenable = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_reenable)

test_connect_basic = pytest.mark.skip("Not yet configured for testing")(_test_module.test_connect_basic)

test_connect_ratelimit = pytest.mark.skip("Not yet configured for testing")(_test_module.test_connect_ratelimit)

test_connect_standard_addr = pytest.mark.skip("Not yet configured for testing")(_test_module.test_connect_standard_addr)

test_connect_transient = pytest.mark.skip("Not yet configured for testing")(_test_module.test_connect_transient)

test_connect_transient_pending = pytest.mark.skip("Not yet configured for testing")(_test_module.test_connect_transient_pending)

test_connection_moved = pytest.mark.skip("Not yet configured for testing")(_test_module.test_connection_moved)

test_connection_timeout = pytest.mark.skip("Not yet configured for testing")(_test_module.test_connection_timeout)

test_dataloss_protection = pytest.mark.skip("Not yet configured for testing")(_test_module.test_dataloss_protection)

test_dataloss_protection_no_broadcast = pytest.mark.skip("Not yet configured for testing")(_test_module.test_dataloss_protection_no_broadcast)

test_disconnect = pytest.mark.skip("Not yet configured for testing")(_test_module.test_disconnect)

test_disconnect_fundee = pytest.mark.skip("Not yet configured for testing")(_test_module.test_disconnect_fundee)

test_disconnect_fundee_v2 = pytest.mark.skip("Not yet configured for testing")(_test_module.test_disconnect_fundee_v2)

test_disconnect_half_signed = pytest.mark.skip("Not yet configured for testing")(_test_module.test_disconnect_half_signed)

test_disconnect_half_signed_v2 = pytest.mark.skip("Not yet configured for testing")(_test_module.test_disconnect_half_signed_v2)

test_disconnect_opener = pytest.mark.skip("Not yet configured for testing")(_test_module.test_disconnect_opener)

test_disconnectpeer = pytest.mark.skip("Not yet configured for testing")(_test_module.test_disconnectpeer)

test_fail_unconfirmed = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fail_unconfirmed)

test_fail_unconfirmed_openchannel2 = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fail_unconfirmed_openchannel2)

test_fee_limits = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fee_limits)

test_feerate_spam = pytest.mark.skip("Not yet configured for testing")(_test_module.test_feerate_spam)

test_feerate_stress = pytest.mark.skip("Not yet configured for testing")(_test_module.test_feerate_stress)

test_forget_channel = pytest.mark.skip("Not yet configured for testing")(_test_module.test_forget_channel)

test_fulfill_incoming_first = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fulfill_incoming_first)

test_fundchannel_start_alternate = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fundchannel_start_alternate)

test_fundee_forget_funding_tx_unconfirmed = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fundee_forget_funding_tx_unconfirmed)

test_fundee_node_unconfirmed = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fundee_node_unconfirmed)

test_funding_all = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_all)

test_funding_all_too_much = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_all_too_much)

test_funding_by_utxos = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_by_utxos)

test_funding_cancel_race = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_cancel_race)

test_funding_change = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_change)

test_funding_close_upfront = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_close_upfront)

test_funding_external_wallet = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_external_wallet)

test_funding_external_wallet_corners = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_external_wallet_corners)

test_funding_fail = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_fail)

test_funding_push = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_push)

test_funding_toolarge = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_toolarge)

test_funding_v2_cancel_race = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_v2_cancel_race)

test_funding_v2_corners = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_v2_corners)

test_funding_while_offline = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_while_offline)

test_htlc_failed_noclose = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_failed_noclose)

test_htlc_retransmit_order = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_retransmit_order)

test_injectonionmessage = pytest.mark.skip("Not yet configured for testing")(_test_module.test_injectonionmessage)

test_last_stable_connection = pytest.mark.skip("Not yet configured for testing")(_test_module.test_last_stable_connection)

test_listpeerchannels_by_scid = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listpeerchannels_by_scid)

test_listpeers_crash = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listpeers_crash)

test_lockin_between_restart = pytest.mark.skip("Not yet configured for testing")(_test_module.test_lockin_between_restart)

test_multichan = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multichan)

test_multichan_stress = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multichan_stress)

test_multifunding_best_effort = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multifunding_best_effort)

test_multifunding_disconnect = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multifunding_disconnect)

test_multifunding_feerates = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multifunding_feerates)

test_multifunding_one = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multifunding_one)

test_multifunding_param_failures = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multifunding_param_failures)

test_multifunding_simple = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multifunding_simple)

test_multifunding_v1_v2_mixed = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multifunding_v1_v2_mixed)

test_multifunding_v2_exclusive = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multifunding_v2_exclusive)

test_multifunding_wumbo = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multifunding_wumbo)

test_multiple_channels = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multiple_channels)

test_mutual_reconnect_race = pytest.mark.skip("Not yet configured for testing")(_test_module.test_mutual_reconnect_race)

test_no_delay = pytest.mark.skip("Not yet configured for testing")(_test_module.test_no_delay)

test_no_fee_estimate = pytest.mark.skip("Not yet configured for testing")(_test_module.test_no_fee_estimate)

test_no_reconnect_awating_unilateral = pytest.mark.skip("Not yet configured for testing")(_test_module.test_no_reconnect_awating_unilateral)

test_nonstatic_channel = pytest.mark.skip("Not yet configured for testing")(_test_module.test_nonstatic_channel)

test_offline = pytest.mark.skip("Not yet configured for testing")(_test_module.test_offline)

test_old_feerate = pytest.mark.skip("Not yet configured for testing")(_test_module.test_old_feerate)

test_onionmessage_forward_fail = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onionmessage_forward_fail)

test_openchannel_init_alternate = pytest.mark.skip("Not yet configured for testing")(_test_module.test_openchannel_init_alternate)

test_opener_feerate_reconnect = pytest.mark.skip("Not yet configured for testing")(_test_module.test_opener_feerate_reconnect)

test_opener_simple_reconnect = pytest.mark.skip("Not yet configured for testing")(_test_module.test_opener_simple_reconnect)

test_opening_tiny_channel = pytest.mark.skip("Not yet configured for testing")(_test_module.test_opening_tiny_channel)

test_pay_disconnect_stress = pytest.mark.skip("Not yet configured for testing")(_test_module.test_pay_disconnect_stress)

test_peer_disconnected_has_featurebits = pytest.mark.skip("Not yet configured for testing")(_test_module.test_peer_disconnected_has_featurebits)

test_peer_disconnected_reflected_in_channel_state = pytest.mark.skip("Not yet configured for testing")(_test_module.test_peer_disconnected_reflected_in_channel_state)

test_peerinfo = pytest.mark.skip("Not yet configured for testing")(_test_module.test_peerinfo)

test_ping_timeout = pytest.mark.skip("Not yet configured for testing")(_test_module.test_ping_timeout)

test_private_channel = pytest.mark.skip("Not yet configured for testing")(_test_module.test_private_channel)

test_private_channel_no_reconnect = pytest.mark.skip("Not yet configured for testing")(_test_module.test_private_channel_no_reconnect)

test_quiescence = pytest.mark.skip("Not yet configured for testing")(_test_module.test_quiescence)

test_reconnect_channel_peers = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reconnect_channel_peers)

test_reconnect_gossiping = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reconnect_gossiping)

test_reconnect_no_additional_transient_failure = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reconnect_no_additional_transient_failure)

test_reconnect_no_update = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reconnect_no_update)

test_reconnect_normal = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reconnect_normal)

test_reconnect_openingd = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reconnect_openingd)

test_reconnect_receiver_add = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reconnect_receiver_add)

test_reconnect_receiver_fulfill = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reconnect_receiver_fulfill)

test_reconnect_remote_sends_no_sigs = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reconnect_remote_sends_no_sigs)

test_reconnect_sender_add = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reconnect_sender_add)

test_reconnect_sender_add1 = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reconnect_sender_add1)

test_reconnect_signed = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reconnect_signed)

test_remote_addr = pytest.mark.skip("Not yet configured for testing")(_test_module.test_remote_addr)

test_remote_addr_disabled = pytest.mark.skip("Not yet configured for testing")(_test_module.test_remote_addr_disabled)

test_remote_addr_port = pytest.mark.skip("Not yet configured for testing")(_test_module.test_remote_addr_port)

test_remote_disconnect = pytest.mark.skip("Not yet configured for testing")(_test_module.test_remote_disconnect)

test_restart_multi_htlc_rexmit = pytest.mark.skip("Not yet configured for testing")(_test_module.test_restart_multi_htlc_rexmit)

test_second_channel = pytest.mark.skip("Not yet configured for testing")(_test_module.test_second_channel)

test_shutdown_awaiting_lockin = pytest.mark.skip("Not yet configured for testing")(_test_module.test_shutdown_awaiting_lockin)

test_shutdown_reconnect = pytest.mark.skip("Not yet configured for testing")(_test_module.test_shutdown_reconnect)

test_update_fee = pytest.mark.skip("Not yet configured for testing")(_test_module.test_update_fee)

test_update_fee_dynamic = pytest.mark.skip("Not yet configured for testing")(_test_module.test_update_fee_dynamic)

test_update_fee_reconnect = pytest.mark.skip("Not yet configured for testing")(_test_module.test_update_fee_reconnect)

test_upgrade_statickey = pytest.mark.skip("Not yet configured for testing")(_test_module.test_upgrade_statickey)

test_upgrade_statickey_fail = pytest.mark.skip("Not yet configured for testing")(_test_module.test_upgrade_statickey_fail)

test_upgrade_statickey_onchaind = pytest.mark.skip("Not yet configured for testing")(_test_module.test_upgrade_statickey_onchaind)

test_v2_open = pytest.mark.skip("Not yet configured for testing")(_test_module.test_v2_open)

test_websocket = pytest.mark.skip("Not yet configured for testing")(_test_module.test_websocket)

test_wss_proxy = pytest.mark.skip("Not yet configured for testing")(_test_module.test_wss_proxy)

test_wumbo_channels = pytest.mark.skip("Not yet configured for testing")(_test_module.test_wumbo_channels)
