# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_clnrest.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
# --- Preamble from config: End ---

from lightning.tests.test_clnrest import test_generate_certificate as _test_generate_certificate

test_generate_certificate = pytest.mark.skip("Not yet configured for testing")(_test_generate_certificate)

from lightning.tests.test_clnrest import test_http_headers as _test_http_headers

test_http_headers = pytest.mark.skip("Not yet configured for testing")(_test_http_headers)

from lightning.tests.test_clnrest import test_large_response as _test_large_response

test_large_response = pytest.mark.skip("Not yet configured for testing")(_test_large_response)

from lightning.tests.test_clnrest import test_list_methods as _test_list_methods

test_list_methods = pytest.mark.skip("Not yet configured for testing")(_test_list_methods)

from lightning.tests.test_clnrest import test_no_auto_start as _test_no_auto_start

test_no_auto_start = pytest.mark.skip("Not yet configured for testing")(_test_no_auto_start)

from lightning.tests.test_clnrest import test_numeric_msat_notification as _test_numeric_msat_notification

test_numeric_msat_notification = pytest.mark.skip("Not yet configured for testing")(_test_numeric_msat_notification)

from lightning.tests.test_clnrest import test_old_params as _test_old_params

test_old_params = pytest.mark.skip("Not yet configured for testing")(_test_old_params)

from lightning.tests.test_clnrest import test_options as _test_options

test_options = pytest.mark.skip("Not yet configured for testing")(_test_options)

from lightning.tests.test_clnrest import test_rpc_method as _test_rpc_method

test_rpc_method = pytest.mark.skip("Not yet configured for testing")(_test_rpc_method)

from lightning.tests.test_clnrest import test_self_signed_certificates as _test_self_signed_certificates

test_self_signed_certificates = pytest.mark.skip("Not yet configured for testing")(_test_self_signed_certificates)

from lightning.tests.test_clnrest import test_unknown_method as _test_unknown_method

test_unknown_method = pytest.mark.skip("Not yet configured for testing")(_test_unknown_method)

from lightning.tests.test_clnrest import test_uses_grpc_plugin_certificates as _test_uses_grpc_plugin_certificates

test_uses_grpc_plugin_certificates = pytest.mark.skip("Not yet configured for testing")(_test_uses_grpc_plugin_certificates)

from lightning.tests.test_clnrest import test_websocket_no_rune as _test_websocket_no_rune

test_websocket_no_rune = pytest.mark.skip("Not yet configured for testing")(_test_websocket_no_rune)

from lightning.tests.test_clnrest import test_websocket_rune_listnotifications as _test_websocket_rune_listnotifications

test_websocket_rune_listnotifications = pytest.mark.skip("Not yet configured for testing")(_test_websocket_rune_listnotifications)

from lightning.tests.test_clnrest import test_websocket_rune_no_listnotifications as _test_websocket_rune_no_listnotifications

test_websocket_rune_no_listnotifications = pytest.mark.skip("Not yet configured for testing")(_test_websocket_rune_no_listnotifications)

from lightning.tests.test_clnrest import test_websocket_rune_readonly as _test_websocket_rune_readonly

test_websocket_rune_readonly = pytest.mark.skip("Not yet configured for testing")(_test_websocket_rune_readonly)

from lightning.tests.test_clnrest import test_websocket_unrestricted_rune as _test_websocket_unrestricted_rune

test_websocket_unrestricted_rune = pytest.mark.skip("Not yet configured for testing")(_test_websocket_unrestricted_rune)

from lightning.tests.test_clnrest import test_websocket_upgrade_header as _test_websocket_upgrade_header

test_websocket_upgrade_header = pytest.mark.skip("Not yet configured for testing")(_test_websocket_upgrade_header)

from lightning.tests.test_clnrest import test_websocket_wrong_rune as _test_websocket_wrong_rune

test_websocket_wrong_rune = pytest.mark.skip("Not yet configured for testing")(_test_websocket_wrong_rune)
