# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_onion.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
# --- Preamble from config: End ---

from lightning.tests.test_onion import test_onion as _test_onion

test_onion = pytest.mark.skip("Not yet configured for testing")(_test_onion)

from lightning.tests.test_onion import test_rendezvous_onion as _test_rendezvous_onion

test_rendezvous_onion = pytest.mark.skip("Not yet configured for testing")(_test_rendezvous_onion)
