from fixtures import *  # noqa: F401,F403

# Import all tests from CLN
from lightning.tests.test_wallet import (
    test_withdraw,
    test_minconf_withdraw,
    test_addfunds_from_block,
    test_txprepare_multi,
    test_txprepare,
    test_reserveinputs,
    test_fundpsbt,
    test_addpsbtoutput,
    test_utxopsbt,
    test_sign_external_psbt,
    test_psbt_version,
    test_sign_and_send_psbt,
    test_txsend,
    test_hsm_secret_encryption,
    test_hsmtool_secret_decryption,
    test_hsmtool_dump_descriptors,
    test_hsmtool_generatehsm,
    test_fundchannel_listtransaction,
    test_withdraw_nlocktime,
    test_withdraw_nlocktime_fuzz,
    test_multiwithdraw_simple,
    test_repro_4258,
    test_withdraw_bech32m,
    test_p2tr_deposit_withdrawal,
    test_upgradewallet,
    test_hsmtool_makerune,
    test_hsmtool_getnodeid,
)
