# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_pay.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_pay as _test_module

test_pay = _test_module.test_pay
test_pay0 = _test_module.test_pay0
test_decode = _test_module.test_decode
test_decodepay = _test_module.test_decodepay
test_sendpay = _test_module.test_sendpay
test_pay_optional_args = _test_module.test_pay_optional_args
test_pay_amounts = _test_module.test_pay_amounts
test_pay_limits = _test_module.test_pay_limits
test_repay = _test_module.test_repay
test_forward = _test_module.test_forward
test_forward_different_fees_and_cltv = _test_module.test_forward_different_fees_and_cltv
test_forward_stats = _test_module.test_forward_stats
test_createonion_rpc = _test_module.test_createonion_rpc
test_sendonion_rpc = _test_module.test_sendonion_rpc
