# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_cln_lsps.py
#
# To update these tests, run the synchronization script.
# To selectively exclude tests, modify the 'test_exclusions.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
# --- Preamble from config: End ---

from lightning.tests.test_cln_lsps import test_lsps0_listprotocols as _test_lsps0_listprotocols

test_lsps0_listprotocols = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_lsps0_listprotocols)

from lightning.tests.test_cln_lsps import test_lsps_service_disabled as _test_lsps_service_disabled

test_lsps_service_disabled = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_lsps_service_disabled)
