# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_splicing.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_splicing as _test_module

test_commit_crash_splice = pytest.mark.skip("Not yet configured for testing")(_test_module.test_commit_crash_splice)

test_invalid_splice = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invalid_splice)

test_splice = pytest.mark.skip("Not yet configured for testing")(_test_module.test_splice)

test_splice_gossip = pytest.mark.skip("Not yet configured for testing")(_test_module.test_splice_gossip)

test_splice_listnodes = pytest.mark.skip("Not yet configured for testing")(_test_module.test_splice_listnodes)

test_splice_nosign = pytest.mark.skip("Not yet configured for testing")(_test_module.test_splice_nosign)

test_splice_out = pytest.mark.skip("Not yet configured for testing")(_test_module.test_splice_out)

test_splice_rbf = pytest.mark.skip("Not yet configured for testing")(_test_module.test_splice_rbf)

test_splice_stuck_htlc = pytest.mark.skip("Not yet configured for testing")(_test_module.test_splice_stuck_htlc)
