# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_gossip.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_gossip as _test_module

test_addgossip = pytest.mark.skip("Not yet configured for testing")(_test_module.test_addgossip)

test_announce_address = pytest.mark.skip("Not yet configured for testing")(_test_module.test_announce_address)

test_announce_and_connect_via_dns = pytest.mark.skip("Not yet configured for testing")(_test_module.test_announce_and_connect_via_dns)

test_announce_dns_suppressed = pytest.mark.skip("Not yet configured for testing")(_test_module.test_announce_dns_suppressed)

test_announce_dns_without_port = pytest.mark.skip("Not yet configured for testing")(_test_module.test_announce_dns_without_port)

test_close_12_block_delay = pytest.mark.skip("Not yet configured for testing")(_test_module.test_close_12_block_delay)

test_connect_by_gossip = pytest.mark.skip("Not yet configured for testing")(_test_module.test_connect_by_gossip)

test_dump_own_gossip = pytest.mark.skip("Not yet configured for testing")(_test_module.test_dump_own_gossip)

test_generate_gossip_store = pytest.mark.skip("Not yet configured for testing")(_test_module.test_generate_gossip_store)

test_getroute_exclude = pytest.mark.skip("Not yet configured for testing")(_test_module.test_getroute_exclude)

test_getroute_exclude_duplicate = pytest.mark.skip("Not yet configured for testing")(_test_module.test_getroute_exclude_duplicate)

test_gossip_addresses = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_addresses)

test_gossip_announce_invalid_block = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_announce_invalid_block)

test_gossip_announce_unknown_block = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_announce_unknown_block)

test_gossip_badsig = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_badsig)

test_gossip_disable_channels = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_disable_channels)

test_gossip_force_broadcast_channel_msgs = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_force_broadcast_channel_msgs)

test_gossip_jsonrpc = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_jsonrpc)

test_gossip_lease_rates = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_lease_rates)

test_gossip_no_backtalk = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_no_backtalk)

test_gossip_no_empty_announcements = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_no_empty_announcements)

test_gossip_not_dying = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_not_dying)

test_gossip_notices_close = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_notices_close)

test_gossip_persistence = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_persistence)

test_gossip_pruning = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_pruning)

test_gossip_query_channel_range = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_query_channel_range)

test_gossip_seeker_autoconnect = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_seeker_autoconnect)

test_gossip_store_compact_noappend = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_store_compact_noappend)

test_gossip_store_compact_on_load = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_store_compact_on_load)

test_gossip_store_load = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_store_load)

test_gossip_store_load_amount_truncated = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_store_load_amount_truncated)

test_gossip_store_load_announce_before_update = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_store_load_announce_before_update)

test_gossip_store_load_complex = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_store_load_complex)

test_gossip_store_load_no_channel_update = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_store_load_no_channel_update)

test_gossip_store_v10_upgrade = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_store_v10_upgrade)

test_gossip_throttle = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_throttle)

test_gossip_timestamp_filter = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_timestamp_filter)

test_gossip_weirdalias = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossip_weirdalias)

test_gossipwith = pytest.mark.skip("Not yet configured for testing")(_test_module.test_gossipwith)

test_incoming_unreasonable = pytest.mark.skip("Not yet configured for testing")(_test_module.test_incoming_unreasonable)

test_node_reannounce = pytest.mark.skip("Not yet configured for testing")(_test_module.test_node_reannounce)

test_only_announce_one_dns = pytest.mark.skip("Not yet configured for testing")(_test_module.test_only_announce_one_dns)

test_parms_listforwards = pytest.mark.skip("Not yet configured for testing")(_test_module.test_parms_listforwards)

test_query_short_channel_id = pytest.mark.skip("Not yet configured for testing")(_test_module.test_query_short_channel_id)

test_report_routing_failure = pytest.mark.skip("Not yet configured for testing")(_test_module.test_report_routing_failure)

test_routetool = pytest.mark.skip("Not yet configured for testing")(_test_module.test_routetool)

test_routing_gossip = pytest.mark.skip("Not yet configured for testing")(_test_module.test_routing_gossip)

test_routing_gossip_reconnect = pytest.mark.skip("Not yet configured for testing")(_test_module.test_routing_gossip_reconnect)

test_seeker_first_peer = pytest.mark.skip("Not yet configured for testing")(_test_module.test_seeker_first_peer)

test_static_tor_onions = pytest.mark.skip("Not yet configured for testing")(_test_module.test_static_tor_onions)

test_topology_leak = pytest.mark.skip("Not yet configured for testing")(_test_module.test_topology_leak)

test_tor_port_onions = pytest.mark.skip("Not yet configured for testing")(_test_module.test_tor_port_onions)
