# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_askrene.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_askrene as _test_module

test_askrene_fake_channeld = pytest.mark.skip("Not yet configured for testing")(_test_module.test_askrene_fake_channeld)

test_fees_dont_exceed_constraints = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fees_dont_exceed_constraints)

test_getroutes = pytest.mark.skip("Not yet configured for testing")(_test_module.test_getroutes)

test_getroutes_auto_localchans = pytest.mark.skip("Not yet configured for testing")(_test_module.test_getroutes_auto_localchans)

test_getroutes_auto_sourcefree = pytest.mark.skip("Not yet configured for testing")(_test_module.test_getroutes_auto_sourcefree)

test_getroutes_fee_fallback = pytest.mark.skip("Not yet configured for testing")(_test_module.test_getroutes_fee_fallback)

test_getroutes_maxdelay = pytest.mark.skip("Not yet configured for testing")(_test_module.test_getroutes_maxdelay)

test_layer_persistence = pytest.mark.skip("Not yet configured for testing")(_test_module.test_layer_persistence)

test_layers = pytest.mark.skip("Not yet configured for testing")(_test_module.test_layers)

test_limits_fake_gossmap = pytest.mark.skip("Not yet configured for testing")(_test_module.test_limits_fake_gossmap)

test_live_spendable = pytest.mark.skip("Not yet configured for testing")(_test_module.test_live_spendable)

test_max_htlc = pytest.mark.skip("Not yet configured for testing")(_test_module.test_max_htlc)

test_min_htlc = pytest.mark.skip("Not yet configured for testing")(_test_module.test_min_htlc)

test_min_htlc_after_excess = pytest.mark.skip("Not yet configured for testing")(_test_module.test_min_htlc_after_excess)

test_real_biases = pytest.mark.skip("Not yet configured for testing")(_test_module.test_real_biases)

test_real_data = pytest.mark.skip("Not yet configured for testing")(_test_module.test_real_data)

test_reserve = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reserve)

test_simple_dummy_channel = pytest.mark.skip("Not yet configured for testing")(_test_module.test_simple_dummy_channel)

test_sourcefree_on_mods = pytest.mark.skip("Not yet configured for testing")(_test_module.test_sourcefree_on_mods)
