# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_xpay.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
# --- Preamble from config: End ---

from lightning.tests.test_xpay import test_fail_after_success as _test_fail_after_success

test_fail_after_success = pytest.mark.skip("Not yet configured for testing")(_test_fail_after_success)

from lightning.tests.test_xpay import test_pay_fakenet as _test_pay_fakenet

test_pay_fakenet = pytest.mark.skip("Not yet configured for testing")(_test_pay_fakenet)

from lightning.tests.test_xpay import test_xpay_bolt12_no_mpp as _test_xpay_bolt12_no_mpp

test_xpay_bolt12_no_mpp = pytest.mark.skip("Not yet configured for testing")(_test_xpay_bolt12_no_mpp)

from lightning.tests.test_xpay import test_xpay_fake_channeld as _test_xpay_fake_channeld

test_xpay_fake_channeld = pytest.mark.skip("Not yet configured for testing")(_test_xpay_fake_channeld)

from lightning.tests.test_xpay import test_xpay_maxdelay as _test_xpay_maxdelay

test_xpay_maxdelay = pytest.mark.skip("Not yet configured for testing")(_test_xpay_maxdelay)

from lightning.tests.test_xpay import test_xpay_maxfee as _test_xpay_maxfee

test_xpay_maxfee = pytest.mark.skip("Not yet configured for testing")(_test_xpay_maxfee)

from lightning.tests.test_xpay import test_xpay_no_mpp as _test_xpay_no_mpp

test_xpay_no_mpp = pytest.mark.skip("Not yet configured for testing")(_test_xpay_no_mpp)

from lightning.tests.test_xpay import test_xpay_partial_msat as _test_xpay_partial_msat

test_xpay_partial_msat = pytest.mark.skip("Not yet configured for testing")(_test_xpay_partial_msat)

from lightning.tests.test_xpay import test_xpay_preapprove as _test_xpay_preapprove

test_xpay_preapprove = pytest.mark.skip("Not yet configured for testing")(_test_xpay_preapprove)

from lightning.tests.test_xpay import test_xpay_selfpay as _test_xpay_selfpay

test_xpay_selfpay = pytest.mark.skip("Not yet configured for testing")(_test_xpay_selfpay)

from lightning.tests.test_xpay import test_xpay_simple as _test_xpay_simple

test_xpay_simple = pytest.mark.skip("Not yet configured for testing")(_test_xpay_simple)

from lightning.tests.test_xpay import test_xpay_slow_mode as _test_xpay_slow_mode

test_xpay_slow_mode = pytest.mark.skip("Not yet configured for testing")(_test_xpay_slow_mode)

from lightning.tests.test_xpay import test_xpay_takeover as _test_xpay_takeover

test_xpay_takeover = pytest.mark.skip("Not yet configured for testing")(_test_xpay_takeover)

from lightning.tests.test_xpay import test_xpay_takeover_null_parms as _test_xpay_takeover_null_parms

test_xpay_takeover_null_parms = pytest.mark.skip("Not yet configured for testing")(_test_xpay_takeover_null_parms)

from lightning.tests.test_xpay import test_xpay_timeout as _test_xpay_timeout

test_xpay_timeout = pytest.mark.skip("Not yet configured for testing")(_test_xpay_timeout)

from lightning.tests.test_xpay import test_xpay_twohop_bug as _test_xpay_twohop_bug

test_xpay_twohop_bug = pytest.mark.skip("Not yet configured for testing")(_test_xpay_twohop_bug)

from lightning.tests.test_xpay import test_xpay_unannounced as _test_xpay_unannounced

test_xpay_unannounced = pytest.mark.skip("Not yet configured for testing")(_test_xpay_unannounced)

from lightning.tests.test_xpay import test_xpay_zeroconf as _test_xpay_zeroconf

test_xpay_zeroconf = pytest.mark.skip("Not yet configured for testing")(_test_xpay_zeroconf)
