# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_askrene.py
#
# To update these tests, run the synchronization script.
# To selectively exclude tests, modify the 'test_exclusions.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
# --- Preamble from config: End ---

from lightning.tests.test_askrene import test_askrene_fake_channeld as _test_askrene_fake_channeld

test_askrene_fake_channeld = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_askrene_fake_channeld)

from lightning.tests.test_askrene import test_fees_dont_exceed_constraints as _test_fees_dont_exceed_constraints

test_fees_dont_exceed_constraints = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_fees_dont_exceed_constraints)

from lightning.tests.test_askrene import test_getroutes as _test_getroutes

test_getroutes = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_getroutes)

from lightning.tests.test_askrene import test_getroutes_auto_localchans as _test_getroutes_auto_localchans

test_getroutes_auto_localchans = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_getroutes_auto_localchans)

from lightning.tests.test_askrene import test_getroutes_auto_sourcefree as _test_getroutes_auto_sourcefree

test_getroutes_auto_sourcefree = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_getroutes_auto_sourcefree)

from lightning.tests.test_askrene import test_getroutes_fee_fallback as _test_getroutes_fee_fallback

test_getroutes_fee_fallback = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_getroutes_fee_fallback)

from lightning.tests.test_askrene import test_getroutes_maxdelay as _test_getroutes_maxdelay

test_getroutes_maxdelay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_getroutes_maxdelay)

from lightning.tests.test_askrene import test_layer_persistence as _test_layer_persistence

test_layer_persistence = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_layer_persistence)

from lightning.tests.test_askrene import test_layers as _test_layers

test_layers = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_layers)

from lightning.tests.test_askrene import test_limits_fake_gossmap as _test_limits_fake_gossmap

test_limits_fake_gossmap = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_limits_fake_gossmap)

from lightning.tests.test_askrene import test_live_spendable as _test_live_spendable

test_live_spendable = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_live_spendable)

from lightning.tests.test_askrene import test_max_htlc as _test_max_htlc

test_max_htlc = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_max_htlc)

from lightning.tests.test_askrene import test_min_htlc as _test_min_htlc

test_min_htlc = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_min_htlc)

from lightning.tests.test_askrene import test_min_htlc_after_excess as _test_min_htlc_after_excess

test_min_htlc_after_excess = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_min_htlc_after_excess)

from lightning.tests.test_askrene import test_real_biases as _test_real_biases

test_real_biases = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_real_biases)

from lightning.tests.test_askrene import test_real_data as _test_real_data

test_real_data = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_real_data)

from lightning.tests.test_askrene import test_reserve as _test_reserve

test_reserve = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_reserve)

from lightning.tests.test_askrene import test_simple_dummy_channel as _test_simple_dummy_channel

test_simple_dummy_channel = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_simple_dummy_channel)

from lightning.tests.test_askrene import test_sourcefree_on_mods as _test_sourcefree_on_mods

test_sourcefree_on_mods = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_sourcefree_on_mods)
