# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_plugin.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_plugin as _test_module

test_all_subscription = pytest.mark.skip("Not yet configured for testing")(_test_module.test_all_subscription)

test_async_rpcmethod = pytest.mark.skip("Not yet configured for testing")(_test_module.test_async_rpcmethod)

test_autoclean = pytest.mark.skip("Not yet configured for testing")(_test_module.test_autoclean)

test_autoclean_batch = pytest.mark.skip("Not yet configured for testing")(_test_module.test_autoclean_batch)

test_autoclean_once = pytest.mark.skip("Not yet configured for testing")(_test_module.test_autoclean_once)

test_autoclean_timer_crash = pytest.mark.skip("Not yet configured for testing")(_test_module.test_autoclean_timer_crash)

test_bcli = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bcli)

test_bitcoin_backend = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bitcoin_backend)

test_bitcoin_bad_estimatefee = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bitcoin_bad_estimatefee)

test_block_added_notifications = pytest.mark.skip("Not yet configured for testing")(_test_module.test_block_added_notifications)

test_channel_opened_notification = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_opened_notification)

test_channel_state_change_history = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_state_change_history)

test_channel_state_changed_bilateral = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_state_changed_bilateral)

test_channel_state_changed_unilateral = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_state_changed_unilateral)

test_coin_movement_notices = pytest.mark.skip("Not yet configured for testing")(_test_module.test_coin_movement_notices)

test_commando = pytest.mark.skip("Not yet configured for testing")(_test_module.test_commando)

test_commando_badrune = pytest.mark.skip("Not yet configured for testing")(_test_module.test_commando_badrune)

test_commando_blacklist = pytest.mark.skip("Not yet configured for testing")(_test_module.test_commando_blacklist)

test_commando_listrunes = pytest.mark.skip("Not yet configured for testing")(_test_module.test_commando_listrunes)

test_commando_rune = pytest.mark.skip("Not yet configured for testing")(_test_module.test_commando_rune)

test_commando_rune_pay_amount = pytest.mark.skip("Not yet configured for testing")(_test_module.test_commando_rune_pay_amount)

test_commando_stress = pytest.mark.skip("Not yet configured for testing")(_test_module.test_commando_stress)

test_custom_notification_topics = pytest.mark.skip("Not yet configured for testing")(_test_module.test_custom_notification_topics)

test_db_hook = pytest.mark.skip("Not yet configured for testing")(_test_module.test_db_hook)

test_db_hook_multiple = pytest.mark.skip("Not yet configured for testing")(_test_module.test_db_hook_multiple)

test_dev_builtin_plugins_unimportant = pytest.mark.skip("Not yet configured for testing")(_test_module.test_dev_builtin_plugins_unimportant)

test_dynamic_args = pytest.mark.skip("Not yet configured for testing")(_test_module.test_dynamic_args)

test_dynamic_option_python_plugin = pytest.mark.skip("Not yet configured for testing")(_test_module.test_dynamic_option_python_plugin)

test_exposesecret = pytest.mark.skip("Not yet configured for testing")(_test_module.test_exposesecret)

test_failing_plugins = pytest.mark.skip("Not yet configured for testing")(_test_module.test_failing_plugins)

test_feature_set = pytest.mark.skip("Not yet configured for testing")(_test_module.test_feature_set)

test_forward_event_notification = pytest.mark.skip("Not yet configured for testing")(_test_module.test_forward_event_notification)

test_hook_chaining = pytest.mark.skip("Not yet configured for testing")(_test_module.test_hook_chaining)

test_hook_crash = pytest.mark.skip("Not yet configured for testing")(_test_module.test_hook_crash)

test_hook_dep = pytest.mark.skip("Not yet configured for testing")(_test_module.test_hook_dep)

test_hook_dep_stable = pytest.mark.skip("Not yet configured for testing")(_test_module.test_hook_dep_stable)

test_htlc_accepted_hook_crash = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_accepted_hook_crash)

test_htlc_accepted_hook_direct_restart = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_accepted_hook_direct_restart)

test_htlc_accepted_hook_fail = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_accepted_hook_fail)

test_htlc_accepted_hook_failmsg = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_accepted_hook_failmsg)

test_htlc_accepted_hook_failonion = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_accepted_hook_failonion)

test_htlc_accepted_hook_forward_restart = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_accepted_hook_forward_restart)

test_htlc_accepted_hook_fwdto = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_accepted_hook_fwdto)

test_htlc_accepted_hook_resolve = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_accepted_hook_resolve)

test_important_plugin = pytest.mark.skip("Not yet configured for testing")(_test_module.test_important_plugin)

test_important_plugin_shutdown = pytest.mark.skip("Not yet configured for testing")(_test_module.test_important_plugin_shutdown)

test_invoice_creation_notification = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoice_creation_notification)

test_invoice_payment_hook = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoice_payment_hook)

test_invoice_payment_hook_hold = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoice_payment_hook_hold)

test_invoice_payment_notification = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoice_payment_notification)

test_keysend_plugin = pytest.mark.skip("Not yet configured for testing")(_test_module.test_keysend_plugin)

test_libplugin = pytest.mark.skip("Not yet configured for testing")(_test_module.test_libplugin)

test_libplugin_deprecated = pytest.mark.skip("Not yet configured for testing")(_test_module.test_libplugin_deprecated)

test_listchannels_broken_message = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listchannels_broken_message)

test_millisatoshi_passthrough = pytest.mark.skip("Not yet configured for testing")(_test_module.test_millisatoshi_passthrough)

test_notify = pytest.mark.skip("Not yet configured for testing")(_test_module.test_notify)

test_openchannel_hook = pytest.mark.skip("Not yet configured for testing")(_test_module.test_openchannel_hook)

test_openchannel_hook_chaining = pytest.mark.skip("Not yet configured for testing")(_test_module.test_openchannel_hook_chaining)

test_openchannel_hook_error_handling = pytest.mark.skip("Not yet configured for testing")(_test_module.test_openchannel_hook_error_handling)

test_option_passthrough = pytest.mark.skip("Not yet configured for testing")(_test_module.test_option_passthrough)

test_option_types = pytest.mark.skip("Not yet configured for testing")(_test_module.test_option_types)

test_pay_plugin = pytest.mark.skip("Not yet configured for testing")(_test_module.test_pay_plugin)

test_peer_connected_remote_addr = pytest.mark.skip("Not yet configured for testing")(_test_module.test_peer_connected_remote_addr)

test_peer_storage = pytest.mark.skip("Not yet configured for testing")(_test_module.test_peer_storage)

test_plugin_command = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_command)

test_plugin_connect_notifications = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_connect_notifications)

test_plugin_connected_hook_chaining = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_connected_hook_chaining)

test_plugin_dir = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_dir)

test_plugin_disable = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_disable)

test_plugin_fail = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_fail)

test_plugin_fail_on_startup = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_fail_on_startup)

test_plugin_feature_announce = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_feature_announce)

test_plugin_hook = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_hook)

test_plugin_nostart = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_nostart)

test_plugin_persist_option = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_persist_option)

test_plugin_shutdown = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_shutdown)

test_plugin_slowinit = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_slowinit)

test_plugin_startdir_lol = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_startdir_lol)

test_pyln_request_notify = pytest.mark.skip("Not yet configured for testing")(_test_module.test_pyln_request_notify)

test_renepay_not_important = pytest.mark.skip("Not yet configured for testing")(_test_module.test_renepay_not_important)

test_replacement_payload = pytest.mark.skip("Not yet configured for testing")(_test_module.test_replacement_payload)

test_restart_on_update = pytest.mark.skip("Not yet configured for testing")(_test_module.test_restart_on_update)

test_rpc_command_hook = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rpc_command_hook)

test_rpc_passthrough = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rpc_passthrough)

test_self_disable = pytest.mark.skip("Not yet configured for testing")(_test_module.test_self_disable)

test_sendpay_notifications = pytest.mark.skip("Not yet configured for testing")(_test_module.test_sendpay_notifications)

test_sendpay_notifications_nowaiter = pytest.mark.skip("Not yet configured for testing")(_test_module.test_sendpay_notifications_nowaiter)

test_sql = pytest.mark.skip("Not yet configured for testing")(_test_module.test_sql)

test_sql_crash = pytest.mark.skip("Not yet configured for testing")(_test_module.test_sql_crash)

test_sql_deprecated = pytest.mark.skip("Not yet configured for testing")(_test_module.test_sql_deprecated)

test_utf8_passthrough = pytest.mark.skip("Not yet configured for testing")(_test_module.test_utf8_passthrough)

test_warning_notification = pytest.mark.skip("Not yet configured for testing")(_test_module.test_warning_notification)

test_watchtower = pytest.mark.skip("Not yet configured for testing")(_test_module.test_watchtower)
