# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_misc.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_misc as _test_module

test_address = pytest.mark.skip("Not yet configured for testing")(_test_module.test_address)

test_bad_onion = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bad_onion)

test_bad_onion_immediate_peer = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bad_onion_immediate_peer)

test_badparam_discretion = pytest.mark.skip("Not yet configured for testing")(_test_module.test_badparam_discretion)

test_bech32_funding = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bech32_funding)

test_bitcoin_failure = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bitcoin_failure)

test_bitcoin_ibd = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bitcoin_ibd)

test_bitcoin_pruned = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bitcoin_pruned)

test_bitcoind_fail_first = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bitcoind_fail_first)

test_bitcoind_feerate_floor = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bitcoind_feerate_floor)

test_bitcoind_goes_backwards = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bitcoind_goes_backwards)

test_blockchaintrack = pytest.mark.skip("Not yet configured for testing")(_test_module.test_blockchaintrack)

test_bolt12_invoice_decode = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bolt12_invoice_decode)

test_check_command = pytest.mark.skip("Not yet configured for testing")(_test_module.test_check_command)

test_checkmessage_pubkey_not_found = pytest.mark.skip("Not yet configured for testing")(_test_module.test_checkmessage_pubkey_not_found)

test_cli = pytest.mark.skip("Not yet configured for testing")(_test_module.test_cli)

test_cli_commando = pytest.mark.skip("Not yet configured for testing")(_test_module.test_cli_commando)

test_cli_multiline_help = pytest.mark.skip("Not yet configured for testing")(_test_module.test_cli_multiline_help)

test_cli_no_argument = pytest.mark.skip("Not yet configured for testing")(_test_module.test_cli_no_argument)

test_commitfee_option = pytest.mark.skip("Not yet configured for testing")(_test_module.test_commitfee_option)

test_config_in_subdir = pytest.mark.skip("Not yet configured for testing")(_test_module.test_config_in_subdir)

test_config_whitespace = pytest.mark.skip("Not yet configured for testing")(_test_module.test_config_whitespace)

test_configfile_before_chdir = pytest.mark.skip("Not yet configured for testing")(_test_module.test_configfile_before_chdir)

test_crashlog = pytest.mark.skip("Not yet configured for testing")(_test_module.test_crashlog)

test_create_gossip_mesh = pytest.mark.skip("Not yet configured for testing")(_test_module.test_create_gossip_mesh)

test_custommsg_triggers_notification = pytest.mark.skip("Not yet configured for testing")(_test_module.test_custommsg_triggers_notification)

test_daemon_option = pytest.mark.skip("Not yet configured for testing")(_test_module.test_daemon_option)

test_datastore = pytest.mark.skip("Not yet configured for testing")(_test_module.test_datastore)

test_datastore_escapeing = pytest.mark.skip("Not yet configured for testing")(_test_module.test_datastore_escapeing)

test_datastore_keylist = pytest.mark.skip("Not yet configured for testing")(_test_module.test_datastore_keylist)

test_datastoreusage = pytest.mark.skip("Not yet configured for testing")(_test_module.test_datastoreusage)

test_db_upgrade = pytest.mark.skip("Not yet configured for testing")(_test_module.test_db_upgrade)

test_decode = pytest.mark.skip("Not yet configured for testing")(_test_module.test_decode)

test_dev_demux = pytest.mark.skip("Not yet configured for testing")(_test_module.test_dev_demux)

test_dev_force_bip32_seed = pytest.mark.skip("Not yet configured for testing")(_test_module.test_dev_force_bip32_seed)

test_emergencyrecover = pytest.mark.skip("Not yet configured for testing")(_test_module.test_emergencyrecover)

test_emergencyrecover_old_format_handling = pytest.mark.skip("Not yet configured for testing")(_test_module.test_emergencyrecover_old_format_handling)

test_emergencyrecoverpenaltytxn = pytest.mark.skip("Not yet configured for testing")(_test_module.test_emergencyrecoverpenaltytxn)

test_even_sendcustommsg = pytest.mark.skip("Not yet configured for testing")(_test_module.test_even_sendcustommsg)

test_fast_shutdown = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fast_shutdown)

test_feerate_arg = pytest.mark.skip("Not yet configured for testing")(_test_module.test_feerate_arg)

test_feerates = pytest.mark.skip("Not yet configured for testing")(_test_module.test_feerates)

test_field_filter = pytest.mark.skip("Not yet configured for testing")(_test_module.test_field_filter)

test_force_feerates = pytest.mark.skip("Not yet configured for testing")(_test_module.test_force_feerates)

test_funding_reorg_get_upset = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_reorg_get_upset)

test_funding_reorg_private = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_reorg_private)

test_funding_reorg_remote_lags = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funding_reorg_remote_lags)

test_getemergencyrecoverdata = pytest.mark.skip("Not yet configured for testing")(_test_module.test_getemergencyrecoverdata)

test_getlog = pytest.mark.skip("Not yet configured for testing")(_test_module.test_getlog)

test_hsm_capabilities = pytest.mark.skip("Not yet configured for testing")(_test_module.test_hsm_capabilities)

test_htlc_in_timeout = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_in_timeout)

test_htlc_out_timeout = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_out_timeout)

test_htlc_sig_persistence = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_sig_persistence)

test_include = pytest.mark.skip("Not yet configured for testing")(_test_module.test_include)

test_io_logging = pytest.mark.skip("Not yet configured for testing")(_test_module.test_io_logging)

test_ipv4_and_ipv6 = pytest.mark.skip("Not yet configured for testing")(_test_module.test_ipv4_and_ipv6)

test_json_error = pytest.mark.skip("Not yet configured for testing")(_test_module.test_json_error)

test_lightningd_still_loading = pytest.mark.skip("Not yet configured for testing")(_test_module.test_lightningd_still_loading)

test_list_features_only = pytest.mark.skip("Not yet configured for testing")(_test_module.test_list_features_only)

test_listaddresses = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listaddresses)

test_listconfigs = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listconfigs)

test_listconfigs_plugins = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listconfigs_plugins)

test_listforwards_ancient = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listforwards_ancient)

test_listforwards_and_listhtlcs = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listforwards_and_listhtlcs)

test_listforwards_wait = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listforwards_wait)

test_listfunds = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listfunds)

test_listhtlcs_wait = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listhtlcs_wait)

test_listtransactions = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listtransactions)

test_log_filter = pytest.mark.skip("Not yet configured for testing")(_test_module.test_log_filter)

test_log_filter_bug = pytest.mark.skip("Not yet configured for testing")(_test_module.test_log_filter_bug)

test_logging = pytest.mark.skip("Not yet configured for testing")(_test_module.test_logging)

test_low_fd_limit = pytest.mark.skip("Not yet configured for testing")(_test_module.test_low_fd_limit)

test_makesecret = pytest.mark.skip("Not yet configured for testing")(_test_module.test_makesecret)

test_malformed_rpc = pytest.mark.skip("Not yet configured for testing")(_test_module.test_malformed_rpc)

test_multiplexed_rpc = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multiplexed_rpc)

test_multirpc = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multirpc)

test_names = pytest.mark.skip("Not yet configured for testing")(_test_module.test_names)

test_new_node_is_mainnet = pytest.mark.skip("Not yet configured for testing")(_test_module.test_new_node_is_mainnet)

test_newaddr = pytest.mark.skip("Not yet configured for testing")(_test_module.test_newaddr)

test_notimestamp_logging = pytest.mark.skip("Not yet configured for testing")(_test_module.test_notimestamp_logging)

test_ping = pytest.mark.skip("Not yet configured for testing")(_test_module.test_ping)

test_preapprove = pytest.mark.skip("Not yet configured for testing")(_test_module.test_preapprove)

test_preapprove_use = pytest.mark.skip("Not yet configured for testing")(_test_module.test_preapprove_use)

test_recover = pytest.mark.skip("Not yet configured for testing")(_test_module.test_recover)

test_recover_command = pytest.mark.skip("Not yet configured for testing")(_test_module.test_recover_command)

test_recover_plugin = pytest.mark.skip("Not yet configured for testing")(_test_module.test_recover_plugin)

test_recoverchannel = pytest.mark.skip("Not yet configured for testing")(_test_module.test_recoverchannel)

test_regtest_upgrade = pytest.mark.skip("Not yet configured for testing")(_test_module.test_regtest_upgrade)

test_relative_config_dir = pytest.mark.skip("Not yet configured for testing")(_test_module.test_relative_config_dir)

test_rescan = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rescan)

test_reserve_enforcement = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reserve_enforcement)

test_restorefrompeer = pytest.mark.skip("Not yet configured for testing")(_test_module.test_restorefrompeer)

test_sendcustommsg = pytest.mark.skip("Not yet configured for testing")(_test_module.test_sendcustommsg)

test_set_feerate_offset = pytest.mark.skip("Not yet configured for testing")(_test_module.test_set_feerate_offset)

test_setconfig = pytest.mark.skip("Not yet configured for testing")(_test_module.test_setconfig)

test_setconfig_access = pytest.mark.skip("Not yet configured for testing")(_test_module.test_setconfig_access)

test_setconfig_changed = pytest.mark.skip("Not yet configured for testing")(_test_module.test_setconfig_changed)

test_signmessage = pytest.mark.skip("Not yet configured for testing")(_test_module.test_signmessage)

test_signmessagewithkey = pytest.mark.skip("Not yet configured for testing")(_test_module.test_signmessagewithkey)

test_staticbackup = pytest.mark.skip("Not yet configured for testing")(_test_module.test_staticbackup)

test_testnet_upgrade = pytest.mark.skip("Not yet configured for testing")(_test_module.test_testnet_upgrade)

test_torv2_in_db = pytest.mark.skip("Not yet configured for testing")(_test_module.test_torv2_in_db)

test_tracing = pytest.mark.skip("Not yet configured for testing")(_test_module.test_tracing)

test_unicode_rpc = pytest.mark.skip("Not yet configured for testing")(_test_module.test_unicode_rpc)

test_unix_socket_path_length = pytest.mark.skip("Not yet configured for testing")(_test_module.test_unix_socket_path_length)

test_version_reexec = pytest.mark.skip("Not yet configured for testing")(_test_module.test_version_reexec)

test_waitblockheight = pytest.mark.skip("Not yet configured for testing")(_test_module.test_waitblockheight)

test_withdraw_misc = pytest.mark.skip("Not yet configured for testing")(_test_module.test_withdraw_misc)
