# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_bookkeeper.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_bookkeeper as _test_module

test_bookkeeper_bad_migration = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeper_bad_migration)

test_bookkeeper_custom_notifs = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeper_custom_notifs)

test_bookkeeper_lease_fee_dupe_migration = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeper_lease_fee_dupe_migration)

test_bookkeeping_closing_subsat_htlcs = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeping_closing_subsat_htlcs)

test_bookkeeping_closing_trimmed_htlcs = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeping_closing_trimmed_htlcs)

test_bookkeeping_descriptions = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeping_descriptions)

test_bookkeeping_external_withdraw_missing = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeping_external_withdraw_missing)

test_bookkeeping_external_withdraws = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeping_external_withdraws)

test_bookkeeping_inspect_mfc_dual_funded = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeping_inspect_mfc_dual_funded)

test_bookkeeping_inspect_multifundchannel = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeping_inspect_multifundchannel)

test_bookkeeping_missed_chans_leases = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeping_missed_chans_leases)

test_bookkeeping_missed_chans_pay_after = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeping_missed_chans_pay_after)

test_bookkeeping_missed_chans_pushed = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeping_missed_chans_pushed)

test_bookkeeping_onchaind_txs = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeping_onchaind_txs)

test_bookkeeping_rbf_withdraw = pytest.mark.skip("Not yet configured for testing")(_test_module.test_bookkeeping_rbf_withdraw)

test_empty_node = pytest.mark.skip("Not yet configured for testing")(_test_module.test_empty_node)

test_rebalance_tracking = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rebalance_tracking)
