# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_splice.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
# --- Preamble from config: End ---

from lightning.tests.test_splice import test_script_splice_in as _test_script_splice_in

test_script_splice_in = pytest.mark.skip("Not yet configured for testing")(_test_script_splice_in)

from lightning.tests.test_splice import test_script_splice_out as _test_script_splice_out

test_script_splice_out = pytest.mark.skip("Not yet configured for testing")(_test_script_splice_out)
