import unittest
from fixtures import *  # noqa: F401,F403

# Import all tests from CLN
from lightning.tests.test_misc import (
    test_names,
    test_db_upgrade,
    test_bitcoin_failure,
    test_bitcoin_ibd,
    test_bitcoin_pruned,
    test_lightningd_still_loading,
    test_ping,
    test_htlc_sig_persistence,
    test_htlc_out_timeout,
    test_htlc_in_timeout,
    test_bech32_funding,
    test_withdraw_misc,
    test_io_logging,
    test_address,
    test_listconfigs,
    test_listconfigs_plugins,
    test_multirpc,
    test_multiplexed_rpc,
    test_malformed_rpc,
    test_cli,
    test_cli_commando,
    test_daemon_option,
    test_cli_no_argument,
    test_blockchaintrack,
    test_funding_reorg_private,
    test_funding_reorg_remote_lags,
    test_funding_reorg_get_upset,
    test_decode,
    test_recover,
    test_rescan,
    test_bitcoind_goes_backwards,
    test_reserve_enforcement,
    test_ipv4_and_ipv6,
    test_feerates,
    test_logging,
    test_crashlog,
    test_configfile_before_chdir,
    test_json_error,
    test_check_command,
    test_bad_onion,
    test_bad_onion_immediate_peer,
    test_newaddr,
    test_bitcoind_fail_first,
    test_bitcoind_feerate_floor,
    test_dev_force_bip32_seed,
    test_dev_demux,
    test_list_features_only as _test_list_features_only,
    test_relative_config_dir as _test_relative_config_dir,
    test_signmessage,
    test_include,
    test_config_in_subdir as _test_config_in_subdir,
    test_testnet_upgrade,
    test_regtest_upgrade,
    test_new_node_is_mainnet,
    test_unicode_rpc,
    test_unix_socket_path_length as _test_unix_socket_path_length,
    test_waitblockheight,
    test_sendcustommsg,
    test_custommsg_triggers_notification,
    test_makesecret,
    test_staticbackup,
    test_recoverchannel,
    test_getemergencyrecoverdata,
    test_emergencyrecover,
    test_recover_plugin,
    test_restorefrompeer,
    test_commitfee_option,
    test_listtransactions,
    test_listfunds,
    test_listforwards_and_listhtlcs,
    test_listforwards_wait,
    test_listforwards_ancient,
    test_version_reexec,
    test_notimestamp_logging,
    test_getlog,
    test_log_filter,
    test_log_filter_bug,
    test_force_feerates,
    test_datastore_escapeing,
    test_datastore,
    test_datastore_keylist,
    test_datastoreusage,
    test_torv2_in_db,
    test_field_filter,
    test_checkmessage_pubkey_not_found,
    test_hsm_capabilities,
    test_feerate_arg,
    test_create_gossip_mesh,
    test_fast_shutdown,
    test_config_whitespace,
    test_setconfig,
    test_recover_command,
    test_even_sendcustommsg,
    test_set_feerate_offset,
    test_low_fd_limit,
    test_preapprove,
    test_preapprove_use,
    test_badparam_discretion,
    test_listaddresses,
)

# Skip tests that don't interact with the signer
test_list_features_only = unittest.skip("Does not interact with signer")(_test_list_features_only)
test_relative_config_dir = unittest.skip("Does not interact with signer")(_test_relative_config_dir)
test_config_in_subdir = unittest.skip("Does not interact with signer")(_test_config_in_subdir)
test_unix_socket_path_length = unittest.skip("Does not interact with signer")(_test_unix_socket_path_length)
