# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_db.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_db as _test_module

test_backfill_scriptpubkeys = pytest.mark.skip("Not yet configured for testing")(_test_module.test_backfill_scriptpubkeys)

test_block_backfill = pytest.mark.skip("Not yet configured for testing")(_test_module.test_block_backfill)

test_channel_htlcs_id_change = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_htlcs_id_change)

test_db_dangling_peer_fix = pytest.mark.skip("Not yet configured for testing")(_test_module.test_db_dangling_peer_fix)

test_db_forward_migrate = pytest.mark.skip("Not yet configured for testing")(_test_module.test_db_forward_migrate)

test_db_sanity_checks = pytest.mark.skip("Not yet configured for testing")(_test_module.test_db_sanity_checks)

test_last_tx_inflight_psbt_upgrade = pytest.mark.skip("Not yet configured for testing")(_test_module.test_last_tx_inflight_psbt_upgrade)

test_last_tx_psbt_upgrade = pytest.mark.skip("Not yet configured for testing")(_test_module.test_last_tx_psbt_upgrade)

test_local_basepoints_cache = pytest.mark.skip("Not yet configured for testing")(_test_module.test_local_basepoints_cache)

test_max_channel_id = pytest.mark.skip("Not yet configured for testing")(_test_module.test_max_channel_id)

test_optimistic_locking = pytest.mark.skip("Not yet configured for testing")(_test_module.test_optimistic_locking)

test_psql_key_value_dsn = pytest.mark.skip("Not yet configured for testing")(_test_module.test_psql_key_value_dsn)

test_scid_upgrade = pytest.mark.skip("Not yet configured for testing")(_test_module.test_scid_upgrade)

test_sqlite3_builtin_backup = pytest.mark.skip("Not yet configured for testing")(_test_module.test_sqlite3_builtin_backup)
