# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_pay.py
#
# To update these tests, run the synchronization script.
# To selectively exclude tests, modify the 'test_exclusions.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
# --- Preamble from config: End ---

from lightning.tests.test_pay import test_blinded_reply_path_scid as _test_blinded_reply_path_scid

test_blinded_reply_path_scid = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_blinded_reply_path_scid)

from lightning.tests.test_pay import test_blindedpath_noaddr as _test_blindedpath_noaddr

test_blindedpath_noaddr = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_blindedpath_noaddr)

from lightning.tests.test_pay import test_blindedpath_privchan as _test_blindedpath_privchan

test_blindedpath_privchan = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_blindedpath_privchan)

from lightning.tests.test_pay import test_bolt11_null_after_pay as _test_bolt11_null_after_pay

test_bolt11_null_after_pay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bolt11_null_after_pay)

from lightning.tests.test_pay import test_channel_receivable as _test_channel_receivable

test_channel_receivable = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_channel_receivable)

from lightning.tests.test_pay import test_channel_spendable as _test_channel_spendable

test_channel_spendable = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_channel_spendable)

from lightning.tests.test_pay import test_channel_spendable_large as _test_channel_spendable_large

test_channel_spendable_large = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_channel_spendable_large)

from lightning.tests.test_pay import test_channel_spendable_receivable_capped as _test_channel_spendable_receivable_capped

test_channel_spendable_receivable_capped = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_channel_spendable_receivable_capped)

from lightning.tests.test_pay import test_createonion_limits as _test_createonion_limits

test_createonion_limits = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_createonion_limits)

from lightning.tests.test_pay import test_createonion_rpc as _test_createonion_rpc

test_createonion_rpc = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_createonion_rpc)

from lightning.tests.test_pay import test_decode as _test_decode

test_decode = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_decode)

from lightning.tests.test_pay import test_decode_expired_bolt12 as _test_decode_expired_bolt12

test_decode_expired_bolt12 = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_decode_expired_bolt12)

from lightning.tests.test_pay import test_decodepay as _test_decodepay

test_decodepay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_decodepay)

from lightning.tests.test_pay import test_decryptencrypteddata as _test_decryptencrypteddata

test_decryptencrypteddata = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_decryptencrypteddata)

from lightning.tests.test_pay import test_delpay_argument_invalid as _test_delpay_argument_invalid

test_delpay_argument_invalid = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_delpay_argument_invalid)

from lightning.tests.test_pay import test_delpay_mixed_status as _test_delpay_mixed_status

test_delpay_mixed_status = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_delpay_mixed_status)

from lightning.tests.test_pay import test_delpay_works as _test_delpay_works

test_delpay_works = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_delpay_works)

from lightning.tests.test_pay import test_dev_rawrequest as _test_dev_rawrequest

test_dev_rawrequest = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_dev_rawrequest)

from lightning.tests.test_pay import test_enableoffer as _test_enableoffer

test_enableoffer = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_enableoffer)

from lightning.tests.test_pay import test_error_returns_blockheight as _test_error_returns_blockheight

test_error_returns_blockheight = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_error_returns_blockheight)

from lightning.tests.test_pay import test_excluded_adjacent_routehint as _test_excluded_adjacent_routehint

test_excluded_adjacent_routehint = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_excluded_adjacent_routehint)

from lightning.tests.test_pay import test_fetch_no_description_offer as _test_fetch_no_description_offer

test_fetch_no_description_offer = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_fetch_no_description_offer)

from lightning.tests.test_pay import test_fetch_no_description_with_amount as _test_fetch_no_description_with_amount

test_fetch_no_description_with_amount = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_fetch_no_description_with_amount)

from lightning.tests.test_pay import test_fetchinvoice as _test_fetchinvoice

test_fetchinvoice = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_fetchinvoice)

from lightning.tests.test_pay import test_fetchinvoice_3hop as _test_fetchinvoice_3hop

test_fetchinvoice_3hop = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_fetchinvoice_3hop)

from lightning.tests.test_pay import test_fetchinvoice_autoconnect as _test_fetchinvoice_autoconnect

test_fetchinvoice_autoconnect = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_fetchinvoice_autoconnect)

from lightning.tests.test_pay import test_fetchinvoice_disconnected_reply as _test_fetchinvoice_disconnected_reply

test_fetchinvoice_disconnected_reply = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_fetchinvoice_disconnected_reply)

from lightning.tests.test_pay import test_fetchinvoice_recurrence as _test_fetchinvoice_recurrence

test_fetchinvoice_recurrence = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_fetchinvoice_recurrence)

from lightning.tests.test_pay import test_fetchinvoice_with_no_quantity as _test_fetchinvoice_with_no_quantity

test_fetchinvoice_with_no_quantity = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_fetchinvoice_with_no_quantity)

from lightning.tests.test_pay import test_fetchinvoice_with_payer_metadata as _test_fetchinvoice_with_payer_metadata

test_fetchinvoice_with_payer_metadata = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_fetchinvoice_with_payer_metadata)

from lightning.tests.test_pay import test_forward as _test_forward

test_forward = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_forward)

from lightning.tests.test_pay import test_forward_different_fees_and_cltv as _test_forward_different_fees_and_cltv

test_forward_different_fees_and_cltv = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_forward_different_fees_and_cltv)

from lightning.tests.test_pay import test_forward_local_failed_stats as _test_forward_local_failed_stats

test_forward_local_failed_stats = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_forward_local_failed_stats)

from lightning.tests.test_pay import test_forward_pad_fees_and_cltv as _test_forward_pad_fees_and_cltv

test_forward_pad_fees_and_cltv = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_forward_pad_fees_and_cltv)

from lightning.tests.test_pay import test_forward_stats as _test_forward_stats

test_forward_stats = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_forward_stats)

from lightning.tests.test_pay import test_htlc_too_dusty_incoming as _test_htlc_too_dusty_incoming

test_htlc_too_dusty_incoming = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_htlc_too_dusty_incoming)

from lightning.tests.test_pay import test_htlc_too_dusty_outgoing as _test_htlc_too_dusty_outgoing

test_htlc_too_dusty_outgoing = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_htlc_too_dusty_outgoing)

from lightning.tests.test_pay import test_htlcs_cltv_only_difference as _test_htlcs_cltv_only_difference

test_htlcs_cltv_only_difference = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_htlcs_cltv_only_difference)

from lightning.tests.test_pay import test_injectpaymentonion_3hop as _test_injectpaymentonion_3hop

test_injectpaymentonion_3hop = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_injectpaymentonion_3hop)

from lightning.tests.test_pay import test_injectpaymentonion_blindedpath as _test_injectpaymentonion_blindedpath

test_injectpaymentonion_blindedpath = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_injectpaymentonion_blindedpath)

from lightning.tests.test_pay import test_injectpaymentonion_failures as _test_injectpaymentonion_failures

test_injectpaymentonion_failures = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_injectpaymentonion_failures)

from lightning.tests.test_pay import test_injectpaymentonion_mpp as _test_injectpaymentonion_mpp

test_injectpaymentonion_mpp = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_injectpaymentonion_mpp)

from lightning.tests.test_pay import test_injectpaymentonion_selfpay as _test_injectpaymentonion_selfpay

test_injectpaymentonion_selfpay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_injectpaymentonion_selfpay)

from lightning.tests.test_pay import test_injectpaymentonion_simple as _test_injectpaymentonion_simple

test_injectpaymentonion_simple = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_injectpaymentonion_simple)

from lightning.tests.test_pay import test_invalid_onion_channel_update as _test_invalid_onion_channel_update

test_invalid_onion_channel_update = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_invalid_onion_channel_update)

from lightning.tests.test_pay import test_invoice_pay_desc_with_quotes as _test_invoice_pay_desc_with_quotes

test_invoice_pay_desc_with_quotes = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_invoice_pay_desc_with_quotes)

from lightning.tests.test_pay import test_keysend as _test_keysend

test_keysend = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_keysend)

from lightning.tests.test_pay import test_keysend_maxfee as _test_keysend_maxfee

test_keysend_maxfee = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_keysend_maxfee)

from lightning.tests.test_pay import test_keysend_routehint as _test_keysend_routehint

test_keysend_routehint = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_keysend_routehint)

from lightning.tests.test_pay import test_keysend_strip_tlvs as _test_keysend_strip_tlvs

test_keysend_strip_tlvs = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_keysend_strip_tlvs)

from lightning.tests.test_pay import test_listpay_result_with_paymod as _test_listpay_result_with_paymod

test_listpay_result_with_paymod = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_listpay_result_with_paymod)

from lightning.tests.test_pay import test_listpays_with_filter_by_status as _test_listpays_with_filter_by_status

test_listpays_with_filter_by_status = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_listpays_with_filter_by_status)

from lightning.tests.test_pay import test_listsendpays_and_listpays_order as _test_listsendpays_and_listpays_order

test_listsendpays_and_listpays_order = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_listsendpays_and_listpays_order)

from lightning.tests.test_pay import test_listsendpays_crash as _test_listsendpays_crash

test_listsendpays_crash = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_listsendpays_crash)

from lightning.tests.test_pay import test_lockup_drain as _test_lockup_drain

test_lockup_drain = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_lockup_drain)

from lightning.tests.test_pay import test_mpp_adaptive as _test_mpp_adaptive

test_mpp_adaptive = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_mpp_adaptive)

from lightning.tests.test_pay import test_mpp_interference_2 as _test_mpp_interference_2

test_mpp_interference_2 = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_mpp_interference_2)

from lightning.tests.test_pay import test_mpp_overload_payee as _test_mpp_overload_payee

test_mpp_overload_payee = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_mpp_overload_payee)

from lightning.tests.test_pay import test_mpp_waitblockheight_routehint_conflict as _test_mpp_waitblockheight_routehint_conflict

test_mpp_waitblockheight_routehint_conflict = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_mpp_waitblockheight_routehint_conflict)

from lightning.tests.test_pay import test_offer as _test_offer

test_offer = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_offer)

from lightning.tests.test_pay import test_offer_deprecated_api as _test_offer_deprecated_api

test_offer_deprecated_api = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_offer_deprecated_api)

from lightning.tests.test_pay import test_offer_experimental_fields as _test_offer_experimental_fields

test_offer_experimental_fields = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_offer_experimental_fields)

from lightning.tests.test_pay import test_offer_path_self as _test_offer_path_self

test_offer_path_self = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_offer_path_self)

from lightning.tests.test_pay import test_offer_paths as _test_offer_paths

test_offer_paths = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_offer_paths)

from lightning.tests.test_pay import test_offer_selfpay as _test_offer_selfpay

test_offer_selfpay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_offer_selfpay)

from lightning.tests.test_pay import test_offer_with_private_channels_multyhop2 as _test_offer_with_private_channels_multyhop2

test_offer_with_private_channels_multyhop2 = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_offer_with_private_channels_multyhop2)

from lightning.tests.test_pay import test_onionmessage_ratelimit as _test_onionmessage_ratelimit

test_onionmessage_ratelimit = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onionmessage_ratelimit)

from lightning.tests.test_pay import test_parallel_channels_reserve as _test_parallel_channels_reserve

test_parallel_channels_reserve = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_parallel_channels_reserve)

from lightning.tests.test_pay import test_partial_payment as _test_partial_payment

test_partial_payment = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_partial_payment)

from lightning.tests.test_pay import test_partial_payment_htlc_loss as _test_partial_payment_htlc_loss

test_partial_payment_htlc_loss = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_partial_payment_htlc_loss)

from lightning.tests.test_pay import test_partial_payment_restart as _test_partial_payment_restart

test_partial_payment_restart = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_partial_payment_restart)

from lightning.tests.test_pay import test_partial_payment_timeout as _test_partial_payment_timeout

test_partial_payment_timeout = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_partial_payment_timeout)

from lightning.tests.test_pay import test_pay as _test_pay

test_pay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay)

from lightning.tests.test_pay import test_pay0 as _test_pay0

test_pay0 = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay0)

from lightning.tests.test_pay import test_pay_amounts as _test_pay_amounts

test_pay_amounts = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_amounts)

from lightning.tests.test_pay import test_pay_avoid_low_fee_chan as _test_pay_avoid_low_fee_chan

test_pay_avoid_low_fee_chan = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_avoid_low_fee_chan)

from lightning.tests.test_pay import test_pay_blockheight_mismatch as _test_pay_blockheight_mismatch

test_pay_blockheight_mismatch = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_blockheight_mismatch)

from lightning.tests.test_pay import test_pay_bolt11_metadata as _test_pay_bolt11_metadata

test_pay_bolt11_metadata = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_bolt11_metadata)

from lightning.tests.test_pay import test_pay_disconnect as _test_pay_disconnect

test_pay_disconnect = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_disconnect)

from lightning.tests.test_pay import test_pay_error_update_fees as _test_pay_error_update_fees

test_pay_error_update_fees = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_error_update_fees)

from lightning.tests.test_pay import test_pay_exclude_node as _test_pay_exclude_node

test_pay_exclude_node = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_exclude_node)

from lightning.tests.test_pay import test_pay_exemptfee as _test_pay_exemptfee

test_pay_exemptfee = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_exemptfee)

from lightning.tests.test_pay import test_pay_fail_unconfirmed_channel as _test_pay_fail_unconfirmed_channel

test_pay_fail_unconfirmed_channel = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_fail_unconfirmed_channel)

from lightning.tests.test_pay import test_pay_get_error_with_update as _test_pay_get_error_with_update

test_pay_get_error_with_update = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_get_error_with_update)

from lightning.tests.test_pay import test_pay_legacy_forward as _test_pay_legacy_forward

test_pay_legacy_forward = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_legacy_forward)

from lightning.tests.test_pay import test_pay_limits as _test_pay_limits

test_pay_limits = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_limits)

from lightning.tests.test_pay import test_pay_manual_exclude as _test_pay_manual_exclude

test_pay_manual_exclude = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_manual_exclude)

from lightning.tests.test_pay import test_pay_maxfee_shadow as _test_pay_maxfee_shadow

test_pay_maxfee_shadow = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_maxfee_shadow)

from lightning.tests.test_pay import test_pay_middle_fail as _test_pay_middle_fail

test_pay_middle_fail = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_middle_fail)

from lightning.tests.test_pay import test_pay_multichannel_use_zeroconf as _test_pay_multichannel_use_zeroconf

test_pay_multichannel_use_zeroconf = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_multichannel_use_zeroconf)

from lightning.tests.test_pay import test_pay_no_secret as _test_pay_no_secret

test_pay_no_secret = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_no_secret)

from lightning.tests.test_pay import test_pay_optional_args as _test_pay_optional_args

test_pay_optional_args = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_optional_args)

from lightning.tests.test_pay import test_pay_partial_msat as _test_pay_partial_msat

test_pay_partial_msat = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_partial_msat)

from lightning.tests.test_pay import test_pay_peer as _test_pay_peer

test_pay_peer = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_peer)

from lightning.tests.test_pay import test_pay_remember_hint as _test_pay_remember_hint

test_pay_remember_hint = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_remember_hint)

from lightning.tests.test_pay import test_pay_retry as _test_pay_retry

test_pay_retry = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_retry)

from lightning.tests.test_pay import test_pay_routeboost as _test_pay_routeboost

test_pay_routeboost = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_routeboost)

from lightning.tests.test_pay import test_pay_routehint_minhtlc as _test_pay_routehint_minhtlc

test_pay_routehint_minhtlc = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_routehint_minhtlc)

from lightning.tests.test_pay import test_pay_unannounced_routehint as _test_pay_unannounced_routehint

test_pay_unannounced_routehint = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_unannounced_routehint)

from lightning.tests.test_pay import test_pay_variants as _test_pay_variants

test_pay_variants = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_variants)

from lightning.tests.test_pay import test_pay_waitblockheight_timeout as _test_pay_waitblockheight_timeout

test_pay_waitblockheight_timeout = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_waitblockheight_timeout)

from lightning.tests.test_pay import test_pay_while_opening_channel as _test_pay_while_opening_channel

test_pay_while_opening_channel = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_pay_while_opening_channel)

from lightning.tests.test_pay import test_payerkey as _test_payerkey

test_payerkey = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_payerkey)

from lightning.tests.test_pay import test_payment_duplicate_uncommitted as _test_payment_duplicate_uncommitted

test_payment_duplicate_uncommitted = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_payment_duplicate_uncommitted)

from lightning.tests.test_pay import test_payment_failed_persistence as _test_payment_failed_persistence

test_payment_failed_persistence = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_payment_failed_persistence)

from lightning.tests.test_pay import test_payment_success_persistence as _test_payment_success_persistence

test_payment_success_persistence = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_payment_success_persistence)

from lightning.tests.test_pay import test_reject_invalid_payload as _test_reject_invalid_payload

test_reject_invalid_payload = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_reject_invalid_payload)

from lightning.tests.test_pay import test_repay as _test_repay

test_repay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_repay)

from lightning.tests.test_pay import test_routehint_tous as _test_routehint_tous

test_routehint_tous = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_routehint_tous)

from lightning.tests.test_pay import test_self_pay as _test_self_pay

test_self_pay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_self_pay)

from lightning.tests.test_pay import test_self_sendpay as _test_self_sendpay

test_self_sendpay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_self_sendpay)

from lightning.tests.test_pay import test_sendinvoice as _test_sendinvoice

test_sendinvoice = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_sendinvoice)

from lightning.tests.test_pay import test_sendinvoice_blindedpath as _test_sendinvoice_blindedpath

test_sendinvoice_blindedpath = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_sendinvoice_blindedpath)

from lightning.tests.test_pay import test_sendonion_rpc as _test_sendonion_rpc

test_sendonion_rpc = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_sendonion_rpc)

from lightning.tests.test_pay import test_sendonion_sendpay as _test_sendonion_sendpay

test_sendonion_sendpay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_sendonion_sendpay)

from lightning.tests.test_pay import test_sendpay as _test_sendpay

test_sendpay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_sendpay)

from lightning.tests.test_pay import test_sendpay_cant_afford as _test_sendpay_cant_afford

test_sendpay_cant_afford = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_sendpay_cant_afford)

from lightning.tests.test_pay import test_sendpay_grouping as _test_sendpay_grouping

test_sendpay_grouping = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_sendpay_grouping)

from lightning.tests.test_pay import test_sendpay_msatoshi_arg as _test_sendpay_msatoshi_arg

test_sendpay_msatoshi_arg = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_sendpay_msatoshi_arg)

from lightning.tests.test_pay import test_sendpays_wait as _test_sendpays_wait

test_sendpays_wait = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_sendpays_wait)

from lightning.tests.test_pay import test_setchannel_all as _test_setchannel_all

test_setchannel_all = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_setchannel_all)

from lightning.tests.test_pay import test_setchannel_enforcement_delay as _test_setchannel_enforcement_delay

test_setchannel_enforcement_delay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_setchannel_enforcement_delay)

from lightning.tests.test_pay import test_setchannel_restart as _test_setchannel_restart

test_setchannel_restart = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_setchannel_restart)

from lightning.tests.test_pay import test_setchannel_routing as _test_setchannel_routing

test_setchannel_routing = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_setchannel_routing)

from lightning.tests.test_pay import test_setchannel_startup_opts as _test_setchannel_startup_opts

test_setchannel_startup_opts = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_setchannel_startup_opts)

from lightning.tests.test_pay import test_setchannel_state as _test_setchannel_state

test_setchannel_state = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_setchannel_state)

from lightning.tests.test_pay import test_setchannel_usage as _test_setchannel_usage

test_setchannel_usage = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_setchannel_usage)

from lightning.tests.test_pay import test_setchannel_zero as _test_setchannel_zero

test_setchannel_zero = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_setchannel_zero)

from lightning.tests.test_pay import test_shadow_routing as _test_shadow_routing

test_shadow_routing = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_shadow_routing)

from lightning.tests.test_pay import test_strip_lightning_suffix_from_inv as _test_strip_lightning_suffix_from_inv

test_strip_lightning_suffix_from_inv = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_strip_lightning_suffix_from_inv)

from lightning.tests.test_pay import test_unreachable_routehint as _test_unreachable_routehint

test_unreachable_routehint = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_unreachable_routehint)

from lightning.tests.test_pay import test_wait_sendpay as _test_wait_sendpay

test_wait_sendpay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_wait_sendpay)
