# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_closing.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_closing as _test_module

test_anchorspend_using_to_remote = pytest.mark.skip("Not yet configured for testing")(_test_module.test_anchorspend_using_to_remote)

test_anysegwit_close_needs_feature = pytest.mark.skip("Not yet configured for testing")(_test_module.test_anysegwit_close_needs_feature)

test_channel_lease_falls_behind = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_lease_falls_behind)

test_channel_lease_lessee_cheat = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_lease_lessee_cheat)

test_channel_lease_lessor_cheat = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_lease_lessor_cheat)

test_channel_lease_post_expiry = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_lease_post_expiry)

test_channel_lease_unilat_closes = pytest.mark.skip("Not yet configured for testing")(_test_module.test_channel_lease_unilat_closes)

test_close_feerate_range = pytest.mark.skip("Not yet configured for testing")(_test_module.test_close_feerate_range)

test_close_twice = pytest.mark.skip("Not yet configured for testing")(_test_module.test_close_twice)

test_close_weight_estimate = pytest.mark.skip("Not yet configured for testing")(_test_module.test_close_weight_estimate)

test_closing_anchorspend_htlc_tx_rbf = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_anchorspend_htlc_tx_rbf)

test_closing_cpfp = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_cpfp)

test_closing_different_fees = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_different_fees)

test_closing_disconnected_notify = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_disconnected_notify)

test_closing_higherfee = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_higherfee)

test_closing_id = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_id)

test_closing_ignore_fee_limits = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_ignore_fee_limits)

test_closing_minfee = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_minfee)

test_closing_negotiation_reconnect = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_negotiation_reconnect)

test_closing_negotiation_step_100pct = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_negotiation_step_100pct)

test_closing_negotiation_step_1sat = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_negotiation_step_1sat)

test_closing_negotiation_step_30pct = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_negotiation_step_30pct)

test_closing_negotiation_step_700sat = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_negotiation_step_700sat)

test_closing_no_anysegwit_retry = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_no_anysegwit_retry)

test_closing_simple = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_simple)

test_closing_specified_destination = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_specified_destination)

test_closing_tx_valid = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_tx_valid)

test_closing_while_disconnected = pytest.mark.skip("Not yet configured for testing")(_test_module.test_closing_while_disconnected)

test_htlc_no_force_close = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_no_force_close)

test_htlc_rexmit_while_closing = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_rexmit_while_closing)

test_invalid_upfront_shutdown_script = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invalid_upfront_shutdown_script)

test_listfunds_after_their_unilateral = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listfunds_after_their_unilateral)

test_onchain_all_dust = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_all_dust)

test_onchain_close_no_p2tr = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_close_no_p2tr)

test_onchain_close_upstream = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_close_upstream)

test_onchain_different_fees = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_different_fees)

test_onchain_dust_out = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_dust_out)

test_onchain_feechange = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_feechange)

test_onchain_first_commit = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_first_commit)

test_onchain_middleman_simple = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_middleman_simple)

test_onchain_middleman_their_unilateral_in = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_middleman_their_unilateral_in)

test_onchain_multihtlc_our_unilateral = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_multihtlc_our_unilateral)

test_onchain_multihtlc_their_unilateral = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_multihtlc_their_unilateral)

test_onchain_p2tr_missed_txs = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_p2tr_missed_txs)

test_onchain_reestablish_reply = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_reestablish_reply)

test_onchain_rexmit_tx = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_rexmit_tx)

test_onchain_slow_anchor = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_slow_anchor)

test_onchain_their_unilateral_out = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_their_unilateral_out)

test_onchain_timeout = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_timeout)

test_onchain_unwatch = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_unwatch)

test_onchaind_replay = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchaind_replay)

test_option_upfront_shutdown_script = pytest.mark.skip("Not yet configured for testing")(_test_module.test_option_upfront_shutdown_script)

test_peer_anchor_push = pytest.mark.skip("Not yet configured for testing")(_test_module.test_peer_anchor_push)

test_penalty_htlc_tx_fulfill = pytest.mark.skip("Not yet configured for testing")(_test_module.test_penalty_htlc_tx_fulfill)

test_penalty_htlc_tx_timeout = pytest.mark.skip("Not yet configured for testing")(_test_module.test_penalty_htlc_tx_timeout)

test_penalty_inhtlc = pytest.mark.skip("Not yet configured for testing")(_test_module.test_penalty_inhtlc)

test_penalty_outhtlc = pytest.mark.skip("Not yet configured for testing")(_test_module.test_penalty_outhtlc)

test_penalty_rbf_normal = pytest.mark.skip("Not yet configured for testing")(_test_module.test_penalty_rbf_normal)

test_permfail = pytest.mark.skip("Not yet configured for testing")(_test_module.test_permfail)

test_permfail_htlc_in = pytest.mark.skip("Not yet configured for testing")(_test_module.test_permfail_htlc_in)

test_permfail_htlc_out = pytest.mark.skip("Not yet configured for testing")(_test_module.test_permfail_htlc_out)

test_permfail_new_commit = pytest.mark.skip("Not yet configured for testing")(_test_module.test_permfail_new_commit)

test_reestablish_closed_channels = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reestablish_closed_channels)

test_segwit_anyshutdown = pytest.mark.skip("Not yet configured for testing")(_test_module.test_segwit_anyshutdown)

test_segwit_shutdown_script = pytest.mark.skip("Not yet configured for testing")(_test_module.test_segwit_shutdown_script)

test_shutdown = pytest.mark.skip("Not yet configured for testing")(_test_module.test_shutdown)

test_you_forgot_closed_channel = pytest.mark.skip("Not yet configured for testing")(_test_module.test_you_forgot_closed_channel)

test_you_forgot_closed_channel_onchain = pytest.mark.skip("Not yet configured for testing")(_test_module.test_you_forgot_closed_channel_onchain)
