# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_cln_rs.py
#
# To update these tests, run the synchronization script.
# To selectively exclude tests, modify the 'test_exclusions.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
# --- Preamble from config: End ---

from lightning.tests.test_cln_rs import test_cln_plugin_reentrant as _test_cln_plugin_reentrant

test_cln_plugin_reentrant = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_cln_plugin_reentrant)

from lightning.tests.test_cln_rs import test_grpc_block_added_notifications as _test_grpc_block_added_notifications

test_grpc_block_added_notifications = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_grpc_block_added_notifications)

from lightning.tests.test_cln_rs import test_grpc_connect as _test_grpc_connect

test_grpc_connect = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_grpc_connect)

from lightning.tests.test_cln_rs import test_grpc_connect_notification as _test_grpc_connect_notification

test_grpc_connect_notification = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_grpc_connect_notification)

from lightning.tests.test_cln_rs import test_grpc_custommsg_notification as _test_grpc_custommsg_notification

test_grpc_custommsg_notification = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_grpc_custommsg_notification)

from lightning.tests.test_cln_rs import test_grpc_decode as _test_grpc_decode

test_grpc_decode = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_grpc_decode)

from lightning.tests.test_cln_rs import test_grpc_default_port_auto_starts as _test_grpc_default_port_auto_starts

test_grpc_default_port_auto_starts = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_grpc_default_port_auto_starts)

from lightning.tests.test_cln_rs import test_grpc_generate_certificate as _test_grpc_generate_certificate

test_grpc_generate_certificate = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_grpc_generate_certificate)

from lightning.tests.test_cln_rs import test_grpc_keysend_routehint as _test_grpc_keysend_routehint

test_grpc_keysend_routehint = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_grpc_keysend_routehint)

from lightning.tests.test_cln_rs import test_grpc_listpeerchannels as _test_grpc_listpeerchannels

test_grpc_listpeerchannels = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_grpc_listpeerchannels)

from lightning.tests.test_cln_rs import test_grpc_wrong_auth as _test_grpc_wrong_auth

test_grpc_wrong_auth = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_grpc_wrong_auth)

from lightning.tests.test_cln_rs import test_plugin_log_levels as _test_plugin_log_levels

test_plugin_log_levels = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_plugin_log_levels)

from lightning.tests.test_cln_rs import test_plugin_options_handle_defaults as _test_plugin_options_handle_defaults

test_plugin_options_handle_defaults = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_plugin_options_handle_defaults)

from lightning.tests.test_cln_rs import test_plugin_start as _test_plugin_start

test_plugin_start = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_plugin_start)

from lightning.tests.test_cln_rs import test_rpc_client as _test_rpc_client

test_rpc_client = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_rpc_client)

from lightning.tests.test_cln_rs import test_rust_plugin_subscribe_wildcard as _test_rust_plugin_subscribe_wildcard

test_rust_plugin_subscribe_wildcard = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_rust_plugin_subscribe_wildcard)
