# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_opening.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_opening as _test_module

test_anchor_min_emergency = pytest.mark.skip("Not yet configured for testing")(_test_module.test_anchor_min_emergency)

test_buy_liquidity_ad_check_bookkeeping = pytest.mark.skip("Not yet configured for testing")(_test_module.test_buy_liquidity_ad_check_bookkeeping)

test_buy_liquidity_ad_no_v2 = pytest.mark.skip("Not yet configured for testing")(_test_module.test_buy_liquidity_ad_no_v2)

test_coinbase_unspendable = pytest.mark.skip("Not yet configured for testing")(_test_module.test_coinbase_unspendable)

test_commitment_feerate = pytest.mark.skip("Not yet configured for testing")(_test_module.test_commitment_feerate)

test_fundchannel_utxo_too_small = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fundchannel_utxo_too_small)

test_funder_contribution_limits = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funder_contribution_limits)

test_funder_options = pytest.mark.skip("Not yet configured for testing")(_test_module.test_funder_options)

test_inflight_dbload = pytest.mark.skip("Not yet configured for testing")(_test_module.test_inflight_dbload)

test_multifunding_all_amount = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multifunding_all_amount)

test_multifunding_v2_best_effort = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multifunding_v2_best_effort)

test_no_anchor_liquidity_ads = pytest.mark.skip("Not yet configured for testing")(_test_module.test_no_anchor_liquidity_ads)

test_openchannel_no_confirmed_inputs_opener = pytest.mark.skip("Not yet configured for testing")(_test_module.test_openchannel_no_confirmed_inputs_opener)

test_openchannel_no_unconfirmed_inputs_accepter = pytest.mark.skip("Not yet configured for testing")(_test_module.test_openchannel_no_unconfirmed_inputs_accepter)

test_opening_explicit_channel_type = pytest.mark.skip("Not yet configured for testing")(_test_module.test_opening_explicit_channel_type)

test_queryrates = pytest.mark.skip("Not yet configured for testing")(_test_module.test_queryrates)

test_rbf_broadcast_close_inflights = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rbf_broadcast_close_inflights)

test_rbf_fails_to_broadcast = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rbf_fails_to_broadcast)

test_rbf_no_overlap = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rbf_no_overlap)

test_rbf_non_last_mined = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rbf_non_last_mined)

test_rbf_reconnect_ack = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rbf_reconnect_ack)

test_rbf_reconnect_init = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rbf_reconnect_init)

test_rbf_reconnect_tx_construct = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rbf_reconnect_tx_construct)

test_rbf_reconnect_tx_sigs = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rbf_reconnect_tx_sigs)

test_rbf_to_chain_before_commit = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rbf_to_chain_before_commit)

test_scid_alias_private = pytest.mark.skip("Not yet configured for testing")(_test_module.test_scid_alias_private)

test_v2_fail_second = pytest.mark.skip("Not yet configured for testing")(_test_module.test_v2_fail_second)

test_v2_open_sigs_out_of_order = pytest.mark.skip("Not yet configured for testing")(_test_module.test_v2_open_sigs_out_of_order)

test_v2_open_sigs_reconnect_1 = pytest.mark.skip("Not yet configured for testing")(_test_module.test_v2_open_sigs_reconnect_1)

test_v2_open_sigs_reconnect_2 = pytest.mark.skip("Not yet configured for testing")(_test_module.test_v2_open_sigs_reconnect_2)

test_v2_open_sigs_restart_while_dead = pytest.mark.skip("Not yet configured for testing")(_test_module.test_v2_open_sigs_restart_while_dead)

test_v2_rbf_abort_channel_opens = pytest.mark.skip("Not yet configured for testing")(_test_module.test_v2_rbf_abort_channel_opens)

test_v2_rbf_abort_retry = pytest.mark.skip("Not yet configured for testing")(_test_module.test_v2_rbf_abort_retry)

test_v2_rbf_liquidity_ad = pytest.mark.skip("Not yet configured for testing")(_test_module.test_v2_rbf_liquidity_ad)

test_v2_rbf_multi = pytest.mark.skip("Not yet configured for testing")(_test_module.test_v2_rbf_multi)

test_v2_rbf_single = pytest.mark.skip("Not yet configured for testing")(_test_module.test_v2_rbf_single)

test_v2_replay_bookkeeping = pytest.mark.skip("Not yet configured for testing")(_test_module.test_v2_replay_bookkeeping)

test_zeroconf_forget = pytest.mark.skip("Not yet configured for testing")(_test_module.test_zeroconf_forget)

test_zeroconf_forward = pytest.mark.skip("Not yet configured for testing")(_test_module.test_zeroconf_forward)

test_zeroconf_mindepth = pytest.mark.skip("Not yet configured for testing")(_test_module.test_zeroconf_mindepth)

test_zeroconf_multichan_forward = pytest.mark.skip("Not yet configured for testing")(_test_module.test_zeroconf_multichan_forward)

test_zeroconf_open = pytest.mark.skip("Not yet configured for testing")(_test_module.test_zeroconf_open)

test_zeroconf_public = pytest.mark.skip("Not yet configured for testing")(_test_module.test_zeroconf_public)

test_zeroreserve = pytest.mark.skip("Not yet configured for testing")(_test_module.test_zeroreserve)

test_zeroreserve_alldust = pytest.mark.skip("Not yet configured for testing")(_test_module.test_zeroreserve_alldust)

test_zeroreserve_mixed = pytest.mark.skip("Not yet configured for testing")(_test_module.test_zeroreserve_mixed)
