# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_runes.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_runes as _test_module

test_badrune = pytest.mark.skip("Not yet configured for testing")(_test_module.test_badrune)

test_blacklistrune = pytest.mark.skip("Not yet configured for testing")(_test_module.test_blacklistrune)

test_checkrune = pytest.mark.skip("Not yet configured for testing")(_test_module.test_checkrune)

test_createrune = pytest.mark.skip("Not yet configured for testing")(_test_module.test_createrune)

test_createrune_per_restriction = pytest.mark.skip("Not yet configured for testing")(_test_module.test_createrune_per_restriction)

test_id_migration = pytest.mark.skip("Not yet configured for testing")(_test_module.test_id_migration)

test_invalid_restrictions = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invalid_restrictions)

test_missing_method_or_nodeid = pytest.mark.skip("Not yet configured for testing")(_test_module.test_missing_method_or_nodeid)

test_nonnumeric_uniqueid = pytest.mark.skip("Not yet configured for testing")(_test_module.test_nonnumeric_uniqueid)

test_rune_bolt11_parse = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rune_bolt11_parse)

test_rune_bolt12_parse = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rune_bolt12_parse)

test_rune_error_messages = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rune_error_messages)

test_rune_method_missing = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rune_method_missing)

test_rune_pay_amount = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rune_pay_amount)

test_showrune_id = pytest.mark.skip("Not yet configured for testing")(_test_module.test_showrune_id)

test_showrunes = pytest.mark.skip("Not yet configured for testing")(_test_module.test_showrunes)
