# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_cln_rs.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_cln_rs as _test_module

test_cln_plugin_reentrant = pytest.mark.skip("Not yet configured for testing")(_test_module.test_cln_plugin_reentrant)

test_grpc_block_added_notifications = pytest.mark.skip("Not yet configured for testing")(_test_module.test_grpc_block_added_notifications)

test_grpc_connect = pytest.mark.skip("Not yet configured for testing")(_test_module.test_grpc_connect)

test_grpc_connect_notification = pytest.mark.skip("Not yet configured for testing")(_test_module.test_grpc_connect_notification)

test_grpc_custommsg_notification = pytest.mark.skip("Not yet configured for testing")(_test_module.test_grpc_custommsg_notification)

test_grpc_decode = pytest.mark.skip("Not yet configured for testing")(_test_module.test_grpc_decode)

test_grpc_default_port_auto_starts = pytest.mark.skip("Not yet configured for testing")(_test_module.test_grpc_default_port_auto_starts)

test_grpc_generate_certificate = pytest.mark.skip("Not yet configured for testing")(_test_module.test_grpc_generate_certificate)

test_grpc_keysend_routehint = pytest.mark.skip("Not yet configured for testing")(_test_module.test_grpc_keysend_routehint)

test_grpc_listpeerchannels = pytest.mark.skip("Not yet configured for testing")(_test_module.test_grpc_listpeerchannels)

test_grpc_wrong_auth = pytest.mark.skip("Not yet configured for testing")(_test_module.test_grpc_wrong_auth)

test_plugin_log_levels = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_log_levels)

test_plugin_options_handle_defaults = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_options_handle_defaults)

test_plugin_start = pytest.mark.skip("Not yet configured for testing")(_test_module.test_plugin_start)

test_rpc_client = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rpc_client)

test_rust_plugin_subscribe_wildcard = pytest.mark.skip("Not yet configured for testing")(_test_module.test_rust_plugin_subscribe_wildcard)
