# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_splicing_disconnect.py
#
# To update these tests, run the synchronization script.
# To selectively exclude tests, modify the 'test_exclusions.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
# --- Preamble from config: End ---

from lightning.tests.test_splicing_disconnect import test_splice_disconnect_commit as _test_splice_disconnect_commit

test_splice_disconnect_commit = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_splice_disconnect_commit)

from lightning.tests.test_splicing_disconnect import test_splice_disconnect_sig as _test_splice_disconnect_sig

test_splice_disconnect_sig = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_splice_disconnect_sig)
