# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_invoices.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_invoices as _test_module

test_amountless_invoice = pytest.mark.skip("Not yet configured for testing")(_test_module.test_amountless_invoice)

test_decode_unknown = pytest.mark.skip("Not yet configured for testing")(_test_module.test_decode_unknown)

test_expiry_startup_crash = pytest.mark.skip("Not yet configured for testing")(_test_module.test_expiry_startup_crash)

test_invoice = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoice)

test_invoice_botched_migration = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoice_botched_migration)

test_invoice_deschash = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoice_deschash)

test_invoice_expiry = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoice_expiry)

test_invoice_preimage = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoice_preimage)

test_invoice_routeboost = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoice_routeboost)

test_invoice_routeboost_private = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoice_routeboost_private)

test_invoice_weirdstring = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoice_weirdstring)

test_invoice_zeroval = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoice_zeroval)

test_invoices_wait_db_migration = pytest.mark.skip("Not yet configured for testing")(_test_module.test_invoices_wait_db_migration)

test_listinvoices_filter = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listinvoices_filter)

test_listinvoices_index = pytest.mark.skip("Not yet configured for testing")(_test_module.test_listinvoices_index)

test_signinvoice = pytest.mark.skip("Not yet configured for testing")(_test_module.test_signinvoice)

test_unified_invoices = pytest.mark.skip("Not yet configured for testing")(_test_module.test_unified_invoices)

test_wait_invoices = pytest.mark.skip("Not yet configured for testing")(_test_module.test_wait_invoices)

test_waitanyinvoice = pytest.mark.skip("Not yet configured for testing")(_test_module.test_waitanyinvoice)

test_waitanyinvoice_reversed = pytest.mark.skip("Not yet configured for testing")(_test_module.test_waitanyinvoice_reversed)

test_waitinvoice = pytest.mark.skip("Not yet configured for testing")(_test_module.test_waitinvoice)
