# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_renepay.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_renepay as _test_module

test_amounts = pytest.mark.skip("Not yet configured for testing")(_test_module.test_amounts)

test_concurrency = pytest.mark.skip("Not yet configured for testing")(_test_module.test_concurrency)

test_description = pytest.mark.skip("Not yet configured for testing")(_test_module.test_description)

test_direction_matters = pytest.mark.skip("Not yet configured for testing")(_test_module.test_direction_matters)

test_errors = pytest.mark.skip("Not yet configured for testing")(_test_module.test_errors)

test_fee_allocation = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fee_allocation)

test_fees = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fees)

test_hardmpp = pytest.mark.skip("Not yet configured for testing")(_test_module.test_hardmpp)

test_hardmpp2 = pytest.mark.skip("Not yet configured for testing")(_test_module.test_hardmpp2)

test_htlc_max = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlc_max)

test_htlcmax0 = pytest.mark.skip("Not yet configured for testing")(_test_module.test_htlcmax0)

test_limits = pytest.mark.skip("Not yet configured for testing")(_test_module.test_limits)

test_local_htlcmax0 = pytest.mark.skip("Not yet configured for testing")(_test_module.test_local_htlcmax0)

test_mpp = pytest.mark.skip("Not yet configured for testing")(_test_module.test_mpp)

test_offer_selfpay = pytest.mark.skip("Not yet configured for testing")(_test_module.test_offer_selfpay)

test_offers = pytest.mark.skip("Not yet configured for testing")(_test_module.test_offers)

test_pay = pytest.mark.skip("Not yet configured for testing")(_test_module.test_pay)

test_previous_sendpays = pytest.mark.skip("Not yet configured for testing")(_test_module.test_previous_sendpays)

test_privatechan = pytest.mark.skip("Not yet configured for testing")(_test_module.test_privatechan)

test_self_pay = pytest.mark.skip("Not yet configured for testing")(_test_module.test_self_pay)

test_shadow_routing = pytest.mark.skip("Not yet configured for testing")(_test_module.test_shadow_routing)

test_simple = pytest.mark.skip("Not yet configured for testing")(_test_module.test_simple)

test_unannounced = pytest.mark.skip("Not yet configured for testing")(_test_module.test_unannounced)
