# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_wallet.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_wallet as _test_module

test_addfunds_from_block = pytest.mark.skip("Not yet configured for testing")(_test_module.test_addfunds_from_block)

test_addpsbtoutput = pytest.mark.skip("Not yet configured for testing")(_test_module.test_addpsbtoutput)

test_fundchannel_listtransaction = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fundchannel_listtransaction)

test_fundpsbt = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fundpsbt)

test_fundpsbt_feerates = pytest.mark.skip("Not yet configured for testing")(_test_module.test_fundpsbt_feerates)

test_hsm_secret_encryption = pytest.mark.skip("Not yet configured for testing")(_test_module.test_hsm_secret_encryption)

test_hsmtool_dump_descriptors = pytest.mark.skip("Not yet configured for testing")(_test_module.test_hsmtool_dump_descriptors)

test_hsmtool_generatehsm = pytest.mark.skip("Not yet configured for testing")(_test_module.test_hsmtool_generatehsm)

test_hsmtool_getnodeid = pytest.mark.skip("Not yet configured for testing")(_test_module.test_hsmtool_getnodeid)

test_hsmtool_makerune = pytest.mark.skip("Not yet configured for testing")(_test_module.test_hsmtool_makerune)

test_hsmtool_secret_decryption = pytest.mark.skip("Not yet configured for testing")(_test_module.test_hsmtool_secret_decryption)

test_minconf_withdraw = pytest.mark.skip("Not yet configured for testing")(_test_module.test_minconf_withdraw)

test_multiwithdraw_simple = pytest.mark.skip("Not yet configured for testing")(_test_module.test_multiwithdraw_simple)

test_onchain_missing_no_p2tr_migrate = pytest.mark.skip("Not yet configured for testing")(_test_module.test_onchain_missing_no_p2tr_migrate)

test_p2tr_deposit_withdrawal = pytest.mark.skip("Not yet configured for testing")(_test_module.test_p2tr_deposit_withdrawal)

test_psbt_version = pytest.mark.skip("Not yet configured for testing")(_test_module.test_psbt_version)

test_repro_4258 = pytest.mark.skip("Not yet configured for testing")(_test_module.test_repro_4258)

test_reserveinputs = pytest.mark.skip("Not yet configured for testing")(_test_module.test_reserveinputs)

test_sign_and_send_psbt = pytest.mark.skip("Not yet configured for testing")(_test_module.test_sign_and_send_psbt)

test_sign_external_psbt = pytest.mark.skip("Not yet configured for testing")(_test_module.test_sign_external_psbt)

test_txprepare = pytest.mark.skip("Not yet configured for testing")(_test_module.test_txprepare)

test_txprepare_feerate = pytest.mark.skip("Not yet configured for testing")(_test_module.test_txprepare_feerate)

test_txprepare_multi = pytest.mark.skip("Not yet configured for testing")(_test_module.test_txprepare_multi)

test_txsend = pytest.mark.skip("Not yet configured for testing")(_test_module.test_txsend)

test_upgradewallet = pytest.mark.skip("Not yet configured for testing")(_test_module.test_upgradewallet)

test_utxopsbt = pytest.mark.skip("Not yet configured for testing")(_test_module.test_utxopsbt)

test_withdraw = pytest.mark.skip("Not yet configured for testing")(_test_module.test_withdraw)

test_withdraw_bech32m = pytest.mark.skip("Not yet configured for testing")(_test_module.test_withdraw_bech32m)

test_withdraw_nlocktime = pytest.mark.skip("Not yet configured for testing")(_test_module.test_withdraw_nlocktime)

test_withdraw_nlocktime_fuzz = pytest.mark.skip("Not yet configured for testing")(_test_module.test_withdraw_nlocktime_fuzz)
