# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_splicing_disconnect.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_splicing_disconnect as _test_module

test_splice_disconnect_commit = pytest.mark.skip("Not yet configured for testing")(_test_module.test_splice_disconnect_commit)

test_splice_disconnect_sig = pytest.mark.skip("Not yet configured for testing")(_test_module.test_splice_disconnect_sig)
