# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_bookkeeper.py
#
# To update these tests, run the synchronization script.
# To selectively exclude tests, modify the 'test_exclusions.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
# --- Preamble from config: End ---

from lightning.tests.test_bookkeeper import test_bookkeeper_bad_migration as _test_bookkeeper_bad_migration

test_bookkeeper_bad_migration = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeper_bad_migration)

from lightning.tests.test_bookkeeper import test_bookkeeper_custom_notifs as _test_bookkeeper_custom_notifs

test_bookkeeper_custom_notifs = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeper_custom_notifs)

from lightning.tests.test_bookkeeper import test_bookkeeper_lease_fee_dupe_migration as _test_bookkeeper_lease_fee_dupe_migration

test_bookkeeper_lease_fee_dupe_migration = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeper_lease_fee_dupe_migration)

from lightning.tests.test_bookkeeper import test_bookkeeping_closing_subsat_htlcs as _test_bookkeeping_closing_subsat_htlcs

test_bookkeeping_closing_subsat_htlcs = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeping_closing_subsat_htlcs)

from lightning.tests.test_bookkeeper import test_bookkeeping_closing_trimmed_htlcs as _test_bookkeeping_closing_trimmed_htlcs

test_bookkeeping_closing_trimmed_htlcs = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeping_closing_trimmed_htlcs)

from lightning.tests.test_bookkeeper import test_bookkeeping_descriptions as _test_bookkeeping_descriptions

test_bookkeeping_descriptions = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeping_descriptions)

from lightning.tests.test_bookkeeper import test_bookkeeping_external_withdraw_missing as _test_bookkeeping_external_withdraw_missing

test_bookkeeping_external_withdraw_missing = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeping_external_withdraw_missing)

from lightning.tests.test_bookkeeper import test_bookkeeping_external_withdraws as _test_bookkeeping_external_withdraws

test_bookkeeping_external_withdraws = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeping_external_withdraws)

from lightning.tests.test_bookkeeper import test_bookkeeping_inspect_mfc_dual_funded as _test_bookkeeping_inspect_mfc_dual_funded

test_bookkeeping_inspect_mfc_dual_funded = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeping_inspect_mfc_dual_funded)

from lightning.tests.test_bookkeeper import test_bookkeeping_inspect_multifundchannel as _test_bookkeeping_inspect_multifundchannel

test_bookkeeping_inspect_multifundchannel = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeping_inspect_multifundchannel)

from lightning.tests.test_bookkeeper import test_bookkeeping_missed_chans_leases as _test_bookkeeping_missed_chans_leases

test_bookkeeping_missed_chans_leases = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeping_missed_chans_leases)

from lightning.tests.test_bookkeeper import test_bookkeeping_missed_chans_pay_after as _test_bookkeeping_missed_chans_pay_after

test_bookkeeping_missed_chans_pay_after = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeping_missed_chans_pay_after)

from lightning.tests.test_bookkeeper import test_bookkeeping_missed_chans_pushed as _test_bookkeeping_missed_chans_pushed

test_bookkeeping_missed_chans_pushed = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeping_missed_chans_pushed)

from lightning.tests.test_bookkeeper import test_bookkeeping_onchaind_txs as _test_bookkeeping_onchaind_txs

test_bookkeeping_onchaind_txs = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeping_onchaind_txs)

from lightning.tests.test_bookkeeper import test_bookkeeping_rbf_withdraw as _test_bookkeeping_rbf_withdraw

test_bookkeeping_rbf_withdraw = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_bookkeeping_rbf_withdraw)

from lightning.tests.test_bookkeeper import test_empty_node as _test_empty_node

test_empty_node = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_empty_node)

from lightning.tests.test_bookkeeper import test_rebalance_tracking as _test_rebalance_tracking

test_rebalance_tracking = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_rebalance_tracking)
