# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_mkfunding.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_mkfunding as _test_module

test_mkfunding_bad_cantaffordfee = pytest.mark.skip("Not yet configured for testing")(_test_module.test_mkfunding_bad_cantaffordfee)

test_mkfunding_bad_input_amount = pytest.mark.skip("Not yet configured for testing")(_test_module.test_mkfunding_bad_input_amount)

test_mkfunding_bad_input_privkey = pytest.mark.skip("Not yet configured for testing")(_test_module.test_mkfunding_bad_input_privkey)

test_mkfunding_bad_input_txid = pytest.mark.skip("Not yet configured for testing")(_test_module.test_mkfunding_bad_input_txid)

test_mkfunding_bad_local_funding_privkey = pytest.mark.skip("Not yet configured for testing")(_test_module.test_mkfunding_bad_local_funding_privkey)

test_mkfunding_bad_privkeys = pytest.mark.skip("Not yet configured for testing")(_test_module.test_mkfunding_bad_privkeys)

test_mkfunding_bad_remote_funding_privkey = pytest.mark.skip("Not yet configured for testing")(_test_module.test_mkfunding_bad_remote_funding_privkey)

test_mkfunding_bad_usage = pytest.mark.skip("Not yet configured for testing")(_test_module.test_mkfunding_bad_usage)

test_mkfunding_good_noabort = pytest.mark.skip("Not yet configured for testing")(_test_module.test_mkfunding_good_noabort)
