# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_reckless.py
#
# To update these tests, run the synchronization script.
# To selectively include/skip tests, modify the 'test_config.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
from fixtures import *  # noqa: F401,F403
# --- Preamble from config: End ---

from lightning.tests import test_reckless as _test_module

test_basic_help = pytest.mark.skip("Not yet configured for testing")(_test_module.test_basic_help)

test_contextual_help = pytest.mark.skip("Not yet configured for testing")(_test_module.test_contextual_help)

test_disable_enable = pytest.mark.skip("Not yet configured for testing")(_test_module.test_disable_enable)

test_install = pytest.mark.skip("Not yet configured for testing")(_test_module.test_install)

test_local_dir_install = pytest.mark.skip("Not yet configured for testing")(_test_module.test_local_dir_install)

test_poetry_install = pytest.mark.skip("Not yet configured for testing")(_test_module.test_poetry_install)

test_search = pytest.mark.skip("Not yet configured for testing")(_test_module.test_search)

test_sources = pytest.mark.skip("Not yet configured for testing")(_test_module.test_sources)

test_tag_install = pytest.mark.skip("Not yet configured for testing")(_test_module.test_tag_install)
