# WARNING: This file is auto-generated by a script. DO NOT EDIT MANUALLY.
# Source file: lightning/tests/test_closing.py
#
# To update these tests, run the synchronization script.
# To selectively exclude tests, modify the 'test_exclusions.yml' file.

# pylint: disable=unused-import,wildcard-import,unused-wildcard-import,invalid-name
# flake8: noqa

# --- Preamble from config: Start ---
import pytest
# --- Preamble from config: End ---

from lightning.tests.test_closing import test_anchorspend_using_to_remote as _test_anchorspend_using_to_remote

test_anchorspend_using_to_remote = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_anchorspend_using_to_remote)

from lightning.tests.test_closing import test_anysegwit_close_needs_feature as _test_anysegwit_close_needs_feature

test_anysegwit_close_needs_feature = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_anysegwit_close_needs_feature)

from lightning.tests.test_closing import test_channel_lease_falls_behind as _test_channel_lease_falls_behind

test_channel_lease_falls_behind = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_channel_lease_falls_behind)

from lightning.tests.test_closing import test_channel_lease_lessee_cheat as _test_channel_lease_lessee_cheat

test_channel_lease_lessee_cheat = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_channel_lease_lessee_cheat)

from lightning.tests.test_closing import test_channel_lease_lessor_cheat as _test_channel_lease_lessor_cheat

test_channel_lease_lessor_cheat = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_channel_lease_lessor_cheat)

from lightning.tests.test_closing import test_channel_lease_post_expiry as _test_channel_lease_post_expiry

test_channel_lease_post_expiry = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_channel_lease_post_expiry)

from lightning.tests.test_closing import test_channel_lease_unilat_closes as _test_channel_lease_unilat_closes

test_channel_lease_unilat_closes = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_channel_lease_unilat_closes)

from lightning.tests.test_closing import test_close_feerate_range as _test_close_feerate_range

test_close_feerate_range = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_close_feerate_range)

from lightning.tests.test_closing import test_close_twice as _test_close_twice

test_close_twice = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_close_twice)

from lightning.tests.test_closing import test_close_weight_estimate as _test_close_weight_estimate

test_close_weight_estimate = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_close_weight_estimate)

from lightning.tests.test_closing import test_closing_anchorspend_htlc_tx_rbf as _test_closing_anchorspend_htlc_tx_rbf

test_closing_anchorspend_htlc_tx_rbf = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_anchorspend_htlc_tx_rbf)

from lightning.tests.test_closing import test_closing_cpfp as _test_closing_cpfp

test_closing_cpfp = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_cpfp)

from lightning.tests.test_closing import test_closing_different_fees as _test_closing_different_fees

test_closing_different_fees = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_different_fees)

from lightning.tests.test_closing import test_closing_disconnected_notify as _test_closing_disconnected_notify

test_closing_disconnected_notify = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_disconnected_notify)

from lightning.tests.test_closing import test_closing_higherfee as _test_closing_higherfee

test_closing_higherfee = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_higherfee)

from lightning.tests.test_closing import test_closing_id as _test_closing_id

test_closing_id = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_id)

from lightning.tests.test_closing import test_closing_ignore_fee_limits as _test_closing_ignore_fee_limits

test_closing_ignore_fee_limits = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_ignore_fee_limits)

from lightning.tests.test_closing import test_closing_minfee as _test_closing_minfee

test_closing_minfee = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_minfee)

from lightning.tests.test_closing import test_closing_negotiation_reconnect as _test_closing_negotiation_reconnect

test_closing_negotiation_reconnect = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_negotiation_reconnect)

from lightning.tests.test_closing import test_closing_negotiation_step_100pct as _test_closing_negotiation_step_100pct

test_closing_negotiation_step_100pct = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_negotiation_step_100pct)

from lightning.tests.test_closing import test_closing_negotiation_step_1sat as _test_closing_negotiation_step_1sat

test_closing_negotiation_step_1sat = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_negotiation_step_1sat)

from lightning.tests.test_closing import test_closing_negotiation_step_30pct as _test_closing_negotiation_step_30pct

test_closing_negotiation_step_30pct = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_negotiation_step_30pct)

from lightning.tests.test_closing import test_closing_negotiation_step_700sat as _test_closing_negotiation_step_700sat

test_closing_negotiation_step_700sat = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_negotiation_step_700sat)

from lightning.tests.test_closing import test_closing_no_anysegwit_retry as _test_closing_no_anysegwit_retry

test_closing_no_anysegwit_retry = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_no_anysegwit_retry)

from lightning.tests.test_closing import test_closing_simple as _test_closing_simple

test_closing_simple = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_simple)

from lightning.tests.test_closing import test_closing_specified_destination as _test_closing_specified_destination

test_closing_specified_destination = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_specified_destination)

from lightning.tests.test_closing import test_closing_tx_valid as _test_closing_tx_valid

test_closing_tx_valid = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_tx_valid)

from lightning.tests.test_closing import test_closing_while_disconnected as _test_closing_while_disconnected

test_closing_while_disconnected = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_closing_while_disconnected)

from lightning.tests.test_closing import test_htlc_no_force_close as _test_htlc_no_force_close

test_htlc_no_force_close = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_htlc_no_force_close)

from lightning.tests.test_closing import test_htlc_rexmit_while_closing as _test_htlc_rexmit_while_closing

test_htlc_rexmit_while_closing = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_htlc_rexmit_while_closing)

from lightning.tests.test_closing import test_invalid_upfront_shutdown_script as _test_invalid_upfront_shutdown_script

test_invalid_upfront_shutdown_script = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_invalid_upfront_shutdown_script)

from lightning.tests.test_closing import test_listfunds_after_their_unilateral as _test_listfunds_after_their_unilateral

test_listfunds_after_their_unilateral = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_listfunds_after_their_unilateral)

from lightning.tests.test_closing import test_onchain_all_dust as _test_onchain_all_dust

test_onchain_all_dust = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_all_dust)

from lightning.tests.test_closing import test_onchain_close_no_p2tr as _test_onchain_close_no_p2tr

test_onchain_close_no_p2tr = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_close_no_p2tr)

from lightning.tests.test_closing import test_onchain_close_upstream as _test_onchain_close_upstream

test_onchain_close_upstream = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_close_upstream)

from lightning.tests.test_closing import test_onchain_different_fees as _test_onchain_different_fees

test_onchain_different_fees = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_different_fees)

from lightning.tests.test_closing import test_onchain_dust_out as _test_onchain_dust_out

test_onchain_dust_out = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_dust_out)

from lightning.tests.test_closing import test_onchain_feechange as _test_onchain_feechange

test_onchain_feechange = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_feechange)

from lightning.tests.test_closing import test_onchain_first_commit as _test_onchain_first_commit

test_onchain_first_commit = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_first_commit)

from lightning.tests.test_closing import test_onchain_middleman_simple as _test_onchain_middleman_simple

test_onchain_middleman_simple = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_middleman_simple)

from lightning.tests.test_closing import test_onchain_middleman_their_unilateral_in as _test_onchain_middleman_their_unilateral_in

test_onchain_middleman_their_unilateral_in = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_middleman_their_unilateral_in)

from lightning.tests.test_closing import test_onchain_multihtlc_our_unilateral as _test_onchain_multihtlc_our_unilateral

test_onchain_multihtlc_our_unilateral = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_multihtlc_our_unilateral)

from lightning.tests.test_closing import test_onchain_multihtlc_their_unilateral as _test_onchain_multihtlc_their_unilateral

test_onchain_multihtlc_their_unilateral = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_multihtlc_their_unilateral)

from lightning.tests.test_closing import test_onchain_p2tr_missed_txs as _test_onchain_p2tr_missed_txs

test_onchain_p2tr_missed_txs = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_p2tr_missed_txs)

from lightning.tests.test_closing import test_onchain_reestablish_reply as _test_onchain_reestablish_reply

test_onchain_reestablish_reply = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_reestablish_reply)

from lightning.tests.test_closing import test_onchain_rexmit_tx as _test_onchain_rexmit_tx

test_onchain_rexmit_tx = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_rexmit_tx)

from lightning.tests.test_closing import test_onchain_slow_anchor as _test_onchain_slow_anchor

test_onchain_slow_anchor = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_slow_anchor)

from lightning.tests.test_closing import test_onchain_their_unilateral_out as _test_onchain_their_unilateral_out

test_onchain_their_unilateral_out = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_their_unilateral_out)

from lightning.tests.test_closing import test_onchain_timeout as _test_onchain_timeout

test_onchain_timeout = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_timeout)

from lightning.tests.test_closing import test_onchain_unwatch as _test_onchain_unwatch

test_onchain_unwatch = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchain_unwatch)

from lightning.tests.test_closing import test_onchaind_replay as _test_onchaind_replay

test_onchaind_replay = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_onchaind_replay)

from lightning.tests.test_closing import test_option_upfront_shutdown_script as _test_option_upfront_shutdown_script

test_option_upfront_shutdown_script = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_option_upfront_shutdown_script)

from lightning.tests.test_closing import test_peer_anchor_push as _test_peer_anchor_push

test_peer_anchor_push = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_peer_anchor_push)

from lightning.tests.test_closing import test_penalty_htlc_tx_fulfill as _test_penalty_htlc_tx_fulfill

test_penalty_htlc_tx_fulfill = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_penalty_htlc_tx_fulfill)

from lightning.tests.test_closing import test_penalty_htlc_tx_timeout as _test_penalty_htlc_tx_timeout

test_penalty_htlc_tx_timeout = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_penalty_htlc_tx_timeout)

from lightning.tests.test_closing import test_penalty_inhtlc as _test_penalty_inhtlc

test_penalty_inhtlc = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_penalty_inhtlc)

from lightning.tests.test_closing import test_penalty_outhtlc as _test_penalty_outhtlc

test_penalty_outhtlc = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_penalty_outhtlc)

from lightning.tests.test_closing import test_penalty_rbf_normal as _test_penalty_rbf_normal

test_penalty_rbf_normal = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_penalty_rbf_normal)

from lightning.tests.test_closing import test_permfail as _test_permfail

test_permfail = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_permfail)

from lightning.tests.test_closing import test_permfail_htlc_in as _test_permfail_htlc_in

test_permfail_htlc_in = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_permfail_htlc_in)

from lightning.tests.test_closing import test_permfail_htlc_out as _test_permfail_htlc_out

test_permfail_htlc_out = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_permfail_htlc_out)

from lightning.tests.test_closing import test_permfail_new_commit as _test_permfail_new_commit

test_permfail_new_commit = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_permfail_new_commit)

from lightning.tests.test_closing import test_reestablish_closed_channels as _test_reestablish_closed_channels

test_reestablish_closed_channels = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_reestablish_closed_channels)

from lightning.tests.test_closing import test_segwit_anyshutdown as _test_segwit_anyshutdown

test_segwit_anyshutdown = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_segwit_anyshutdown)

from lightning.tests.test_closing import test_segwit_shutdown_script as _test_segwit_shutdown_script

test_segwit_shutdown_script = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_segwit_shutdown_script)

from lightning.tests.test_closing import test_shutdown as _test_shutdown

test_shutdown = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_shutdown)

from lightning.tests.test_closing import test_you_forgot_closed_channel as _test_you_forgot_closed_channel

test_you_forgot_closed_channel = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_you_forgot_closed_channel)

from lightning.tests.test_closing import test_you_forgot_closed_channel_onchain as _test_you_forgot_closed_channel_onchain

test_you_forgot_closed_channel_onchain = pytest.mark.skip("All tests disabled - initial import farm setup")(_test_you_forgot_closed_channel_onchain)
