#!/bin/bash

# Assign the first command line argument to a variable
networkType=$1

baseDir="/usr/local"
descriptor=$(git describe --always)
dateTimeStamp=$(date +"%Y%m%d%H%M%S")
leafDir="vls-hsmd-${descriptor}-${dateTimeStamp}"
installDir="${baseDir}/${leafDir}"

mkdir -p "$installDir"
make install PREFIX="$installDir"

# add a lib subdir for the demo_signer STM32 image
mkdir -p "$installDir/lib"

echo "Installation completed in directory: $installDir"

# If an arg is provided set the symbolic link
if [[ -n $networkType ]]; then
    rm -f "/usr/local/vls-hsmd-${networkType}"
    cd /usr/local && ln -s "$leafDir" "vls-hsmd-${networkType}"
    echo "${networkType} setup completed."
fi
