#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -yy -qq \
     eatmydata postgresql libsqlite3-dev pigz zip git \
     autoconf automake build-essential libtool \
     python3-pkg-resources \
     python3 \
     python3-dev \
     python3-pip \
     python3-setuptools \
     python3-mako \
  ca-certificates sudo tzdata python3 python3-pip python3-setuptools python3-dev python-is-python3 \
  protobuf-compiler protobuf-compiler-grpc libgrpc++-dev pkg-config
pip3 install --break-system-packages --upgrade pip
pip3 install --break-system-packages --user poetry==1.3.2 poetry-core==1.4.0
