#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -yy -qq git ca-certificates sudo tzdata python3 python3-pip python3-setuptools python3-dev python-is-python3 protobuf-compiler protobuf-compiler-grpc libgrpc++-dev pkg-config
pip3 install --upgrade pip
