#!/bin/bash

set -e

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -yy -qq \
     autoconf \
     automake \
     build-essential \
     ca-certificates \
     eatmydata \
     git \
     jq \
     libgrpc++-dev \
     libsqlite3-dev \
     libtool \
     man-db \
     pigz \
     pkg-config \
     postgresql \
     protobuf-compiler \
     protobuf-compiler-grpc \
     python-is-python3 \
     python3 \
     python3-dev \
     python3-mako \
     python3-pip \
     python3-pkg-resources \
     python3-setuptools \
     sudo \
     tzdata \
     zip \
     $(NULL)
