#!/bin/bash

# Use default timeout if none set
: ${TIMEOUT:=1200}

THETEST=$1

export \
PYTHONPATH=\
$PWD/contrib/pyln-client:\
$PWD/contrib/pyln-testing:\
$PWD/contrib/pyln-proto \
TEST_KEEPDIR=1 \
TEST_DEBUG=1 \
DEVELOPER=1 \
SLOW_MACHINE=0 \
RUST_BACKTRACE=1 \
&& printenv > $TEST_DIR/ENV.log && \
pytest \
$THETEST \
-v --timeout=$TIMEOUT --timeout_method=signal -p no:logging -s
