#!/bin/bash

THETEST=$1

PYTHONPATH=\
$PWD/contrib/pyln-client:\
$PWD/contrib/pyln-testing:\
$PWD/contrib/pyln-proto \
TEST_KEEPDIR=1 \
TEST_DEBUG=1 \
DEVELOPER=1 \
SLOW_MACHINE=0 \
RUST_BACKTRACE=1 \
pytest \
$THETEST \
-v --timeout=300 --timeout_method=thread -p no:logging -s --help
