#!/bin/bash

set -e

make_link()
{
    have=$(realpath --relative-to=$2 $1)
    ln -sf $have $2
}

[ -d "./bin" ] || mkdir ./bin

make_link bin/remote_hsmd_vls lightning/lightningd/
make_link bin/remote_hsmd_socket lightning/lightningd/
make_link bin/remote_hsmd_serial lightning/lightningd/
